### ISSUE TITLE
[Package Request]: Trippy 0.7.0

### ISSUE THREAD

**Issue by fujiapple852** [microsoft/winget-pkgs#100719]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/fujiapple852/trippy/releases/tag/0.7.0
Publisher: https://github.com/fujiapple852
Package Name: Trippy (trip.exe)
Description: A network diagnostic tool
Package Version: 0.7.0
Installer URL: https://github.com/fujiapple852/trippy/releases/download/0.7.0/trippy-0.7.0-x86_64-pc-windows-msvc.zip

Note that I tried to create this myself using `wingetcreate` but was not able to get it to work (I understood that a zip'd `exe` should work?):

```
PS C:\Users\vboxuser> wingetcreate new https://github.com/fujiapple852/trippy/releases/download/0.7.0/trippy-0.7.0-x86_64-pc-windows-msvc.zip
Downloading and parsing: https://github.com/fujiapple852/trippy/releases/download/0.7.0/trippy-0.7.0-x86_64-pc-windows-msvc.zip...
Failed to parse the package from [https://github.com/fujiapple852/trippy/releases/download/0.7.0/trippy-0.7.0-x86_64-pc-windows-msvc.zip]
```

**Comment by BrandonWanHuanSheng** [comment]
It also same for me. It doesn't work also.

**Comment by fujiapple852** [comment]
Any thought on how we can diagnose the problem?

**Comment by fujiapple852** [comment]
Ah the issue is that I didn't read the instructions properly, trippy on Windows is [compressed](https://github.com/fujiapple852/trippy/blob/d8749c0bb094e9c74a5d5697a3602c3e3026c7e5/.github/workflows/release.yml#L98) with `7z` which is not supported by winget.  

I'll have to look at moving to another supported format, or perhaps an uncompressed package.

**Comment by fujiapple852** [comment]
I tried using `7z a -tzip "$staging.zip" "$staging"` but that didn't fix it

**Comment by BrandonWanHuanSheng** [comment]
This is an examples of windows portable package
![Screenshot (122)](https://user-images.githubusercontent.com/118059864/229136881-5074032c-7ab4-4a4c-8b3a-5c583bd9ed5a.png)

**Comment by mdanish-kh** [comment]
I've created the package PR, but converted it to draft because there is a known issue with nested portable packages where Path variable isn't updated correctly in non-developer mode / installation from non-admin shells in Windows.

The fix for the above issue is already merged in a PR https://github.com/microsoft/winget-cli/pull/3002 and will likely be available in the next release of WinGet, so I would say we hold off adding this package until the fix appears in the next release for best user experience.

As for the issue with winget-create, I've create an issue (linked above) over at the winget-create repo.

**Comment by fujiapple852** [comment]
Thank you very much @mdanish-kh!  

Does the nested portable package issue you mention explain the CI failures in your PR?  I don't really understand https://github.com/microsoft/winget-pkgs/pull/101363#issuecomment-1494563472 which makes me think it is expecting an installer?

In case it matters; whilst I now build the package as a real `zip` archive using `7z a -tzip "$staging.zip" "$staging"` (see [here](https://github.com/fujiapple852/trippy/blob/418a41eab0614bea3765f30609ecbc99e705b72b/.github/workflows/release.yml#L101)), the `0.7.0` release [archive](https://github.com/fujiapple852/trippy/releases/download/0.7.0/trippy-0.7.0-x86_64-pc-windows-msvc.zip) was built with `7z a "$staging.zip" "$staging"` so is not a real `zip` archive, despite the name.  I only mention it as `7z` archives are not supported by `wingetcreate`.

**Comment by BrandonWanHuanSheng** [comment]
Hold Off first.

**Comment by mdanish-kh** [comment]
> Does the nested portable package issue you mention explain the CI failures in your PR? 

I don't think the two issues are related.

> I don't really understand [#101363 (comment)](https://github.com/microsoft/winget-pkgs/pull/101363#issuecomment-1494563472) which makes me think it is expecting an installer?

@stephengillie would be able to clarify more, but I think the CI environment is expecting `trip` command to return a non-error code after installation to ascertain the installation was successful.


> In case it matters; whilst I now build the package as a real zip archive using 7z a -tzip "$staging.zip" "$staging" (see [here](https://github.com/fujiapple852/trippy/blob/418a41eab0614bea3765f30609ecbc99e705b72b/.github/workflows/release.yml#L101)), the 0.7.0 release [archive](https://github.com/fujiapple852/trippy/releases/download/0.7.0/trippy-0.7.0-x86_64-pc-windows-msvc.zip) was built with 7z a "$staging.zip" "$staging" so is not a real zip archive, despite the name. I only mention it as 7z archives are not supported by wingetcreate.

I don't think it matters, the fix for the nested portable issue got merged in winget-create's codebase in PR https://github.com/microsoft/winget-create/pull/356 (tested with your package and it works) and the fix will likely appear in the next release for winget-create. I'm not sure when the next release will ship out but until then you could try out [other manifest authoring tools](https://github.com/microsoft/winget-pkgs#authoring-a-manifest) if you wish

**Comment by fujiapple852** [comment]
That’s great, thanks @mdanish-kh

**Comment by fujiapple852** [comment]
I saw some recent [activity](https://github.com/microsoft/winget-pkgs/pull/101363#issuecomment-1529044376) on the PR @mdanish-kh, it says "Validation has completed" but looks like it's still failing.  Is it still just a case of waiting or is some action needed?  Thanks!

**Comment by mdanish-kh** [comment]
@fujiapple852 The PR is good to go; if I convert it from draft to "Ready for review", it will get merged into the repo. The only catch is that the package will work correctly only on the latest preview build which is [WinGet v1.5.1081](https://github.com/microsoft/winget-cli/releases/tag/v1.5.1081-preview) (and higher versions when they come out). Ideally, I would like to wait until 1.5 is a stable release before we merge the package to avoid issues with people on the current stable release but if you want we can merge the package now (just know it won't work for people on the current stable 1.4 release)

**Comment by BrandonWanHuanSheng** [comment]
I also have some pull-request still in draft. I am also waiting for winget to roll out the update.

**Comment by fujiapple852** [comment]
Hi there @BrandonWanHuanSheng @mdanish-kh @stephengillie I wonder if you can help with something. 

Trippy requires allowing some incoming ICMP traffic in Windows defender and so I’d like to explore the possibility of enabling this access at installation time. This has become something if a FAQ for Windows users of Trippy. 

Is this something winget allows (both technically and as a policy)?  

According to ChatGPT it can be done by adding something like the following (untested, so just to illustrate the idea):

```
{
  "Id": "YourPublisher.YourApp",
  "Name": "YourApp",
  "Version": "1.0",
  "Publisher": "YourPublisher",
  "Description": "YourApp description",
  "Homepage": "https://yourapp.com",
  "License": "MIT",
  "LicenseUrl": "https://yourapp.com/license",
  "Installers": [
    {
      "Architecture": "x64",
      "InstallerType": "custom",
      "InstallerUrl": "https://yourapp.com/download/yourapp.exe",
      "InstallerSha256": "<SHA256 hash>",
      "Custom": {
        "Silent": "/S /C \"netsh advfirewall firewall add rule name=\"ICMPv4\" protocol=icmpv4:8,any dir=in action=allow & netsh advfirewall firewall add rule name=\"ICMPv4 Echo Reply\" protocol=icmpv4:0,any dir=in action=allow & netsh advfirewall firewall add rule name=\"ICMPv4 Time Exceeded\" protocol=icmpv4:11,any dir=in action=allow & netsh advfirewall firewall add rule name=\"ICMPv6\" protocol=icmpv6:8,any dir=in action=allow & netsh advfirewall firewall add rule name=\"ICMPv6 Echo Reply\" protocol=icmpv6:0,any dir=in action=allow & netsh advfirewall firewall add rule name=\"ICMPv6 Time Exceeded\" protocol=icmpv6:11,any dir=in action=allow\"",
        "SilentWithProgress": "/S /C \"netsh advfirewall firewall add rule name=\"ICMPv4\" protocol=icmpv4:8,any dir=in action=allow & netsh advfirewall firewall add rule name=\"ICMPv4 Echo Reply\" protocol=icmpv4:0,any dir=in action=allow & netsh advfirewall firewall add rule name=\"ICMPv4 Time Exceeded\" protocol=icmpv4:11,any dir=in action=allow & netsh advfirewall firewall add rule name=\"ICMPv6\" protocol=icmpv6:8,any dir=in action=allow & netsh advfirewall firewall add rule name=\"ICMPv6 Echo Reply\" protocol=icmpv6:0,any dir=in action=allow & netsh advfirewall firewall add rule name=\"ICMPv6 Time Exceeded\" protocol=icmpv6:11,any dir=in action=allow\""
      }
    }
  ]
}
```

**Comment by mdanish-kh** [comment]
@fujiapple852 I don't think that the snippet provided by ChatGPT will work. Since `Trippy` is a portable app, WinGet only takes the responsibility of extracting the zip archive into a directory, making that directory available in the PATH variable and its metadata available in the registry.

Your use case is something that's looks a good fit for the [`winget configure`](https://learn.microsoft.com/en-us/windows/package-manager/configuration/) command provided there's a resource available for controlling Windows Defender (that I don't know of but maybe @denelon could help here)

At the very least though, we can add [`InstallationNotes:`](https://github.com/microsoft/winget-pkgs/blob/efb1a6eac2058ff3f17db392326a99a6295e35aa/manifests/f/FujiApple/Trippy/0.8.0/FujiApple.Trippy.locale.en-US.yaml#L64) to the manifest informing the user post-installation that this package requires enabling ICMP traffic in Windows Defender. It would look something like: 

![zoomit](https://github.com/microsoft/winget-pkgs/assets/88161975/ca61626b-bed7-4abd-8ec1-eb3da92d3f76)

**Comment by fujiapple852** [comment]
Thanks @mdanish-kh, I agree that adding a message is likely the best option.  What i'll do is create FAQ entry in README that gives details of how to do this which can then be linked from the `InstallationNotes` as you suggest.

**Comment by mdanish-kh** [comment]
@fujiapple852 You can raise the PR anytime you'd like :)

**Comment by fujiapple852** [comment]
@mdanish-kh I've updated the manifest to have:

```
InstallationNotes: You *must* configure the Windows Defender firewall to allow incoming ICMP traffic, see https://github.com/fujiapple852/trippy#windows-defender
```

I've also bumped the version to the new `0.9.0` release at the same time:

https://github.com/microsoft/winget-pkgs/pull/129163
