### ISSUE TITLE
[Package Request]: Typst

### ISSUE THREAD

**Issue by n-gao** [microsoft/winget-pkgs#102292]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/typst/typst/releases
Publisher: Typst GmbH i.G.
Package Name: Typst
Description: A new markup-based typesetting system that is powerful and easy to learn.
Package Version: 0.2.0
Installer URL: https://github.com/typst/typst/releases/download/v0.2.0/typst-x86_64-pc-windows-msvc.zip

**Comment by mdanish-kh** [comment]
I've created the PR for the package but holding off the merge process as there is a known issue with nested portables where the PATH variable isn't updated correctly in non-admin shells / non-developer mode.

Fortunately, the fix for the above issue is already resolved in https://github.com/microsoft/winget-cli/pull/3002 and we're just waiting on the fix to appear in the next release of winget

**Comment by BrandonWanHuanSheng** [comment]
I am also holding off the merge on version 0.3.0. Current latest is version 0.3.0. Due to github released a new version of Typst.Typst.

**Comment by BrandonWanHuanSheng** [comment]
It look like yesterday, the author roll up the Typst.Typst update which is 0.4.0.

**Comment by BrandonWanHuanSheng** [comment]
Hmmm. It looks like update requests issues did not appear due to the main issue packages did not merge because there is an issue with Relative File Path
