### ISSUE TITLE
OBS Studio (exit code 6) another program using this

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#105965]
If we can confirm exit code 6 is returned because another program is using OBS Studio, we should add the appropriate expected return code to the manifest.

```text
 i had this problem with  Exitcode: 6 and obsstudio through winget upgrade obsproject.obsstudio. i found out it was because of skype. used powershell. winget upgrade obsproject.obsstudio didn't work. used cmd as admin. winget upgrade obsproject.obsstudio didn't work. restarted. winget upgrade obsproject.obsstudio didn't work. deinstalled obsstudio. winget install obsproject.obsstudio didn't work. downloaded the exe from obsstudio-site, executed it and surprisingly it said, it can't be installed because of ... SKYPE? maybe skype used obsproject as webcam, idk. killed skype. started winget install obsproject.obsstudio. worked.
```

_Originally posted by @hueldoeu in https://github.com/microsoft/winget-cli/issues/245#issuecomment-1535125237_

**Comment by hueldoeu** [comment]
closing skype wasn't difficult. i am satisfied so far with ms products. what really is annoying is e. g. 
Microsoft Visual C++ 2005 Redistributable                  Microsoft.VCRedist.2005.x86 8.0.59193    8.0.61001    winget
Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.30… Microsoft.VCRedist.2013.x86 12.0.30501.0 12.0.40664.0 winget

i can't winget upgrade them (wingen't upgrade). the thunderbirds are my problem. i f***ed up my windows 10. next pc won't have this problem. what really is strange is that microsoft doesn't have control on it's own products like i said these Microsoft Visual C++ Redistributable OR MS Teams! doesn't microsoft want to be the better zoom? i have been at so many online-seminars. teams is a pain in the a**. even skype wasn't too bad. teams is difficult to use. difficult to handle. first version of zoom was SUPER! winget upgrade teams isn't also possible. thats why i will delete it soon on this pc and use the browser-version of teams. the android version of teams is also BAD.
[winget.txt](https://github.com/microsoft/winget-pkgs/files/11400201/winget.txt)

**Comment by Trenly** [comment]
> If we can confirm exit code 6 is returned because another program is using OBS Studio, we should add the appropriate expected return code to the manifest.

The code is already in the manifest -
https://github.com/microsoft/winget-pkgs/blob/9079fe0d5924279749c00f0cbbc4d80d26dfdfb1/manifests/o/OBSProject/OBSStudio/29.1.0/OBSProject.OBSStudio.installer.yaml#L14-L16

**Comment by Trenly** [comment]
> the thunderbirds are my problem.

Based on the file you provided, it seems like the Thunderbird issues may be happening because there are two separate versions of Thunderbird installed. I know that `winget uninstall Mozilla.Thunderbird -v 78.5.1` won't work in your scenario, but perhaps `winget uninstall 'Mozilla Thunderbird 78.5.1 (x64 de)'` will work. Then you will have only one version of Thunderbird which should allow you to run the upgrade

**Comment by hueldoeu** [comment]
> > the thunderbirds are my problem.
> 
> Based on the file you provided, it seems like the Thunderbird issues may be happening because there are two separate versions of Thunderbird installed. I know that `winget uninstall Mozilla.Thunderbird -v 78.5.1` won't work in your scenario, but perhaps `winget uninstall 'Mozilla Thunderbird 78.5.1 (x64 de)'` will work. Then you will have only one version of Thunderbird which should allow you to run the upgrade

well ....... you have to emphasise MY and not the word problem. the thunderbird is my own problem and shouldn't stress anybody besides me. it's my own fault and was just an experiment. i have a mail-adress similar to gmail but i pay for it and it's from my country. i access the mails via imap and i wanted to have a mail-client like thunderbird which starts from my SOHO-server so that every client-pc can access the mails. i failed. i lost. i have installed thunderbird on the server, i have set up the target of where the mails will be downloaded (server is better because huge free storage and centralized). didn't really pay out and then i have installed thunderbird on each client-PC and access on the data and save the data on the server. this also didn't work so well. so i decided to just connect windows mail and calender (soon called one outlook or sth like that) and thunderbird on every client-PC directly with the mail-server over imap smtp and yes, this works. sadly the data will be downloaded on every pc simultanously, so i decided to create an extra partition on an extra drive and yes thunderbird is downloading and uploading everything on the extra partition, where it's installed.

i am very sure that with a new installation the thunderbird-problem will be solved. i learned from my mistakes and that maybe in the future there will be a software for collaborative working on one mail-adress via imap and smtp but not now. 

i have to buy new PCs for my office since windows 11 isn't supported so the thunderbird problem will be solved.

i really wish a revolution for e-mail like i can easily set up a mail server with postfix, but it will not be accepted by the most freemails like gmail or yahoo mail or outlook and i wish something like i have set up a mail adress by some company, university,  something like that and they have some extra software because it's not hard using email-clients en masse but the data will be stored multiple times each on a client-PC. why not stored on a server, which gets the mail via imap and WAN and the client-PCs  just communicate with the SOHO-server in LAN and the data is only saved on the SOHO-server and ofcourse the e-mail server.

**Comment by kristapsesterlins** [comment]
Morning,

Stumbled upon this issue and thanks to Process Monitor I was able to determine why the installer was failing with the message:
"Installer failed with exit code: 6"
```
Found OBS Studio [OBSProject.OBSStudio] Version 29.1.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 6
Files modified by the installer are currently in use by a different application. Exit the applications then try again.
```

Turns out that Microsoft Teams (Teams.exe) was somehow interfering with the installer. Closing it solved the issue.

![Untitled](https://github.com/microsoft/winget-pkgs/assets/92995128/16cb9869-bf9d-4b8f-bb9c-bb7e87ee5a5c)

**Comment by Dum4G** [comment]
OBS has built-in functionality to mimic a webcam as an output device. So it's about every messaging app that may use it. I have succesfully updated after closing Discord and Telegram. Thanks for the tip

**Comment by hi-im-na** [comment]
closing the Microsoft Edge works for me

**Comment by carlosm3011** [comment]
I found another blocker, LogiTune, an app by Logitech to manage certain Logitech hardware.

**Comment by PurplProto** [comment]
> OBS has built-in functionality to mimic a webcam as an output device. So it's about every messaging app that may use it. I have succesfully updated after closing Discord and Telegram. Thanks for the tip

This statement is holding up. For me, it was Nvidia Broadcast blocking the installation.

**Comment by clicks** [comment]
For whatever reason, but in my case it was "Podman Desktop" which was blocking the installation.
Is it possible to enforce it?

**Comment by WegnerDan** [comment]
Garmin Express and Deepl also seem to block upgrading.

**Comment by hueldoeu** [comment]
> How do you guys figure out which program is preventing it from upgrading? are you just trial and erroring by disabling certain apps through your terminal? Especially keen to know how you got to that screenshot page @kristapsesterlins

exclusion principle through task manager

**Comment by kristapsesterlins** [comment]
> How do you guys figure out which program is preventing it from upgrading? are you just trial and erroring by disabling certain apps through your terminal? Especially keen to know how you got to that screenshot page @kristapsesterlins

Hi,

The tool in the screenshot is Process Monitor - https://learn.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by hueldoeu** [comment]
even edge wants to be an attention-guy
![Screenshot 2024-03-24 180448](https://github.com/microsoft/winget-pkgs/assets/11273667/06775b89-0ba0-4e6c-9a8e-b064bbd7948e)
the problem is now that i can't deactivate edge. restarting the computer didn't help.

**Comment by SnoepNFTs** [comment]
> even edge wants to be an attention-guy ![Screenshot 2024-03-24 180448](https://private-user-images.githubusercontent.com/11273667/316327038-06775b89-0ba0-4e6c-9a8e-b064bbd7948e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMTIyNzgsIm5iZiI6MTcxMTMxMTk3OCwicGF0aCI6Ii8xMTI3MzY2Ny8zMTYzMjcwMzgtMDY3NzViODktMGJhMC00ZTZjLTlhOGUtYjA2NGJiZDc5NDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDIwMjYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYTJhYWQyZmYyOTg4NzI5ZWZhYjI5Njg3Y2Q5YzAwMTQ4ZWM3YmUyYmNkYTUzMmRhYjc4NjZkZDVhZWZlZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JJ5MSH57JW_5Jb-r-YWR1kWcOqW2Aj336-3GoH3SaDU) the problem is now that i can't deactivate edge. restarting the computer didn't help.

Technically you could remove it if by using christitustech his window utility in an elevated powershell type: `irm christitus.com/win | iex`  > head to tweaks > advanced tweaks and remove it from there. if you are heavily invested into office365, Onedrive and MS teams I wouldn't recommend this as it can break things. but if you don't its a safe option to do so

**Comment by hueldoeu** [comment]
> > even edge wants to be an attention-guy ![Screenshot 2024-03-24 180448](https://private-user-images.githubusercontent.com/11273667/316327038-06775b89-0ba0-4e6c-9a8e-b064bbd7948e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMTIyNzgsIm5iZiI6MTcxMTMxMTk3OCwicGF0aCI6Ii8xMTI3MzY2Ny8zMTYzMjcwMzgtMDY3NzViODktMGJhMC00ZTZjLTlhOGUtYjA2NGJiZDc5NDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDIwMjYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYTJhYWQyZmYyOTg4NzI5ZWZhYjI5Njg3Y2Q5YzAwMTQ4ZWM3YmUyYmNkYTUzMmRhYjc4NjZkZDVhZWZlZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JJ5MSH57JW_5Jb-r-YWR1kWcOqW2Aj336-3GoH3SaDU) the problem is now that i can't deactivate edge. restarting the computer didn't help.
> 
> Technically you could remove it by using christitustech his window utility in an elevated powershell type: `irm christitus.com/win | iex` > head to tweaks > advanced tweaks > select remove ms edge and run the tweaks > edge should now be removed. If you are heavily invested into Office365, Onedrive and MS teams I wouldn't recommend this as it can break things. but if you don't its a safe option to do so

had to cmd =>
tasklist
taskkill /f /im msedge.exe
taskkill /f /im msedgewebview2.exe
https://www.youtube.com/watch?v=WeJNOypsWDM
one task was very nasty (msedgewebview2) and when i have killed it in the task manager, it killed other msedgewebview2's too and revived them instantly. i looked for the path and renamen the file msedgewebview2.exe in
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\122.0.2365.92
to msedgewebview22.exe. then i killed msedgewebview2 in the task manager again. it didn't appear again. then cmd => winget upgrade obsproject.obsstudio and upgrade was successful.
i rerenamed msedgewebview22 back to msedgewebview2, but doubleclick on it or opening edge didn't allow it to come back to task manager, it was missing. 
restarting helped to revive msedgewebview2.exe.

**Comment by DoronLGN** [comment]
I encountered this problem as well, and found that Facebook's Messenger app was using OBS for some reason.

**Comment by journeym** [comment]
I have the same problem
For me it was Playnite

**Comment by Trenly** [comment]
The response code has been updated for a while now, so WinGet should show the correct error message.

###### Close with reason: Resolved;

**Comment by Atario** [comment]
Another for the list:  Samsung Magician

**Comment by TechnoStone** [comment]
Another for the list: Nvidia Broadcast (C:\Program Files\NVIDIA Corporation\NVIDIA Broadcast\NvVirtualCamera\NVIDIA Broadcast.exe)

**Comment by rasa** [comment]
When I run `%Temp%\WinGet\OBSProject.OBSStudio.30.2.3 >OBS-Studio-30.2.3-Windows-Installer.exe` manually, this pops up:
```
---------------------------
OBS Studio 30.2.3 Setup
---------------------------
OBS files are being used by the following applications:



Intel(R) Arc(TM) Control Assist


Please close these applications to continue setup.
---------------------------
Retry   Cancel   
---------------------------
```

**Comment by hueldoeu** [comment]
i think the in-built update function of obs works quite well
![Image](https://github.com/user-attachments/assets/120ae0ed-ef51-40e5-9404-95aba65866c4)
sometimes i use cmd => winget search OBSProject.OBSStudio on specific PCs or Laptops with windows 10/11 and as everyone knows it doesn't work become some programs are using obs as a virtual webcam but on some specific PCs or Laptops it can be over 7 programs which are running in background and running in RAM like zoom, skype, edge, asus armoury, nvidia broadcast, ...

but since the last few times where obs itself asked me to upgrade, i used the update function of obs itself (instead of cmd => winget upgrade or unigetUI) and it took more time to be honest but it never caused any problems and i've never had to close any programs which prevent the update of obs.

**Comment by laurencee** [comment]
Wavebox also causes this

**Comment by kjbetz** [comment]
@rasa's comment led me to run `winget upgrade 'OBS Studio' -i` adding the `-i` or `--interactive` tag which does this: "Request interactive installation; user input may be needed"

This went through the full installer and showed me the exact application causing the problem. In my case it was Microsoft Edge internet browser. I closed Edge and then was able to hit the `Retry` button and it went through the upgrade successfully.

**Comment by oapy123** [comment]
Same here, -i opened the full installer which showed me that Google Chrome and LogiTune were using OBS.  This is very annoying having to to kill other tasks to update.  
![Image](https://github.com/user-attachments/assets/dcd06703-fed4-47c5-88cd-73b90a0bb4a8)

I think I may just not use WinGet to update OBS and instead rely on the built in OBS updater when it prompts me upon opening the program when an update is available.  Doing it that way took literally 10 seconds and I didn't have to close Chrome or LogiTune.

**Comment by aurexav** [comment]
For me, it's ASUS Node JS framework.

**Comment by de-served** [comment]
For `MS Edge` goto `Settings > System and Performance` and disable `Fast startup` and `Continue background apps when Edge is closed`

**Comment by hueldoeu** [comment]
> For `MS Edge` goto `Settings > System and Performance` and disable `Fast startup` and `Continue background apps when Edge is closed`

![Image](https://github.com/user-attachments/assets/c90834a9-036f-4220-b0d2-343efed8e43d)

**Comment by edler-san** [comment]
LM Studio is another culprit.

**Comment by fazzaan** [comment]
If the application using the OBS module is critical to whatever you're doing, you can unload the dll module file manually.
I used System Informer. 

WARNING: This could make your application unstable so think about it before following these steps.
In my case, Chrome was the offender, Chrome uses a tonne of separated process threads so it wasn't an issue to kill off or interfere with the process that was engaging the OBS files.

Here's a screenshot of what I did:

![Image](https://github.com/user-attachments/assets/68058927-495e-4d78-a11f-3842c4372536)

Steps:
1. Run winget upgrade -i OBS 
2. Click to start the upgrade process inside the OBS installer wizard window
3. A window pops up to tell you which apps are using OBS files
4. Open System Informer and click Find Handles or DLLs
5. Search for OBS and look for the offending process (in my case, chrome.exe)
6. Right click on the process in the list and choose "go to process". The window focus will switch back to the main System Informer list of processes, and the chosen process is selected.
7. Press Enter or right click on the process. 
8. In the new window that popped up, go to the Modules tab. Search for OBS, right click on the module and click "unload".
9. Now you can click "retry" in the OBS installation window.

Do remember that this method is probably a bad idea if it's a mission critical application that mustn't crash.
It worked fine for me though.

**Comment by sjain882** [comment]
I keep getting "Files modified by the installer are currently in use by a different application. Exit the applications then try again." even when OBS is quit. It seems that having ANY browser running (Firefox/Edge/Chrome) causes this. Any ideas why?

**Comment by Skgland** [comment]
> I keep getting "Files modified by the installer are currently in use by a different application. Exit the applications then try again." even when OBS is quit. It seems that having ANY browser running (Firefox/Edge/Chrome) causes this. Any ideas why?

My suspicion would be that the browsers enumerate available cameras on startup and that causes the OBS virtual camera to get loaded.

**Comment by beria-pl** [comment]
In my case it was Signal Desktop app
