### ISSUE TITLE
[Package Issue]: SublimeHQ.SublimeText.4 version unknown during upgrade

### ISSUE THREAD

**Issue by lutzroeder** [microsoft/winget-pkgs#106111]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The package shows with an `Unknown` version and a newer version available but never updates to that version. Running the installer manually without winget does not resolve the issue. 

### Steps to reproduce

1. `winget install SublimeHQ.SublimeText.4`
2. `winget upgrade -s winget --all`
`1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.`
3. `winget uninstall SublimeHQ.SublimeText.4`
4. Install Sublime Text 4 from [https://www.sublimetext.com/download_thanks?target=win-x64](https://www.sublimetext.com/download_thanks?target=win-x64)
5. `winget upgrade -s winget --all`
`1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.`
6. 'winget list --name "Sublime"`
```
Name         Id                      Version Available    Source
----------------------------------------------------------------
Sublime Text SublimeHQ.SublimeText.4 Unknown 4.0.0.414300 winget
``` 

### Actual behavior

The package shows with an `Unknown` version and a newer version available but never updates to a valid version. Running the installer manually without winget does not resolve the issue. 

### Expected behavior

The package version should be shown. When installing the package manually without winget, it should not show up as an error during `winget upgrade --all`.

### Environment

```raw
Windows Package Manager (Preview) v1.5.1081-preview
Windows: Windows.Desktop v10.0.22621.1555
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1081.0
```
```


### Screenshots and Logs

_No response_

**Comment by Trenly** [comment]
This is because the publisher does not write a value into the registry to indicate the version. Because winget uses the registry to determine which application and versions are installed, it sees that there is no version information available and presents it as "Unknown". The best way to fix this is for the publisher of the software to update the installer so it writes the DisplayVersion registry key.

[Policy] Installer Issue

**Comment by lutzroeder** [comment]
@jskinner @wbond @dpjohnst do you have some context or any pointers who can help investigate?

**Comment by koitsu** [comment]
https://github.com/sublimehq/sublime_text/issues/1114 and https://github.com/sublimehq/sublime_text/issues/5272 , both of which document this problem with ST3 (and ST4 uses the same installer, InnoSetup).  Note that the oldest ticket is 7 years old.

The fact the SublimeHQ folks have not addressed this in seven years is disheartening at best, especially when the fix is as simple as adding a single line to their .iss file that contains the actual build/version number (which they certainly known at .iss-build-time).

**Comment by lutzroeder** [comment]
Duplicate of #126287
