### ISSUE TITLE
[Package Issue]: 7zip.7zip

### ISSUE THREAD

**Issue by aurel-bul** [microsoft/winget-pkgs#107748]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Winget's --silent switch doesn't work with the new version of 7zip (23.00) submitted last week.

### Steps to reproduce

`winget install 7zip.7zip --silent`

### Actual behavior

![image](https://github.com/microsoft/winget-pkgs/assets/85838056/3a3fe50a-0a5b-40e2-8ea6-b18366499717)

### Expected behavior

Silent install in the background

### Environment

```raw
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2965
System Architecture: X64

Logs: %TEMP%\WinGet\defaultState

User Settings: %LOCALAPPDATA%\Microsoft\WinGet\Settings\defaultState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by BrandonWanHuanSheng** [comment]
I think that application is Alpha.

**Comment by BrandonWanHuanSheng** [comment]
From,Brandon Wan From: Code.Sent: Wednesday, May 24, 2023 11:20 AMTo: microsoft/winget-pkgsCc: Brandon Wan; CommentSubject: Re: [microsoft/winget-pkgs] [Package Issue]: 7zip.7zip (Issue #107748) The manifest has the 2300 urls despite being labeled as 2100, so that explains why my separate 7zipalpha pr was labeled as a duplicate.In order to fix this the correct urls will need to be provided.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by BrandonWanHuanSheng** [comment]
It looks like I am fixing on it. The pull request might automatically popup.
