### ISSUE TITLE
[Update Request]: 7zip.7zip

### ISSUE THREAD

**Issue by Holt59** [microsoft/winget-pkgs#108197]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

7zip.7zip

### Package Version

22.01

### Please describe the changes you would like to see

The manifest for the installer specifies a `7z` commands but the command is not available after install. I'd like the `7z` cli to be available after installation (through update of PATH or something else).

Current workaround is to add the path to `7z` to `PATH` manually.

**Comment by Trenly** [comment]
* Related to https://github.com/microsoft/winget-cli/issues/549


It seems this is because the installer doesn’t add it to PATH. Because it is an installer, winget has no control over the install location and therefore doesn’t know what directory to add to PATH.

Are there switches for 7zip that will tell the installer to add it to path?
