### ISSUE TITLE
[Update Request]: Windows Terminal

### ISSUE THREAD

**Issue by brkerez** [microsoft/winget-pkgs#108419]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.WindowsTerminal

### Package Version

1.17.11461.0

### Please describe the changes you would like to see

There is a new release 1.17.11461.0 available.
https://github.com/microsoft/terminal/releases

**Comment by BrandonWanHuanSheng** [comment]
Sorry, Unable to update them. It look like it depend on Microsoft.UI.Xaml.2.7

**Comment by brkerez** [comment]
I'm not very familiar with package possibilities and dependency management, so I apologize for the possibly stupid question :)  
Cannot be Xaml.2..7 added by creating dependency on `9P5VK8KZB5QZ` ?

![image](https://github.com/microsoft/winget-pkgs/assets/313735/5e9d6dd9-a3d4-4d8b-a3cc-37b29cf07711)

**Comment by BrandonWanHuanSheng** [comment]
See #108350. They might need to check the Windows Store Commit.

**Comment by denelon** [comment]
We currently don't have support for "cross-source" dependencies. Microsoft.UI.XAML is a "framework" package in the Microsoft Store and is automatically included in the install flow via the Microsoft Store. We're looking at the options we have here to address the gap.

**Comment by denelon** [comment]
https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.8.4

It looks like they don't have an "installer".

**Comment by BrandonWanHuanSheng** [comment]
The setup always use this domains URL https://tlu.dl.delivery.mp.microsoft.com. The link is very quickly expired after download. Most of the Windows 10 Features, Preview Updates, Extension, Appx, Dynamic Update and Some Cumulative Update is download from over there. Windows Setup also use this link also. From,Brandon Wan From: Demitrius NelonSent: Wednesday, 31 May, 2023 1:08 AMTo: microsoft/winget-pkgsCc: Brandon Wan; CommentSubject: Re: [microsoft/winget-pkgs] [Update Request]: Windows Terminal (Issue #108419) https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.8.4It looks like they don't have an "installer".—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by BrandonWanHuanSheng** [comment]
When I press the download Windows 11 Version 22H2, it look like windows is downloading additional cab and appx  components for the setup.

**Comment by Trenly** [comment]
[Policy] Dependencies
