### ISSUE TITLE
[Package Issue]: BlenderFoundation.Blender

### ISSUE THREAD

**Issue by d4kir92** [microsoft/winget-pkgs#110150]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

i have blender installed via STEAM

and it show up in winget as update, but it is latest version

### Steps to reproduce

install blender via steam

### Actual behavior

unknown version

### Expected behavior

latest version

### Environment

```raw
Windows-Paket-Manager v1.4.11071
Windows: Windows.Desktop v10.0.22621.1848
X64
Paket: Microsoft.DesktopAppInstaller v1.19.11071.0
```

### Screenshots and Logs

![image](https://github.com/microsoft/winget-pkgs/assets/23246564/281fb4c0-0f65-4c57-bc86-463cadcdddc7)

**Comment by krystofkrticka** [comment]
The issue is Steam... Because when you open appwiz.cpl and try to find anything from Steam the version column is empty.

**Comment by d4kir92** [comment]
so it can be tracked by this?
![image](https://github.com/microsoft/winget-pkgs/assets/23246564/71d8c1d6-3f3a-4cc9-8afc-b12b0281f450)

properties of the exe file*

**Comment by krystofkrticka** [comment]
I don't know but probably not for now. Unless they are already specing this feature.

**Comment by stephengillie** [comment]
If I'm understanding correctly, the issue is that Steam as a package manager doesn't write version data to the Registry, and this prevents WinGet from correctly detecting the installed version. And the proposed solution is to read this data from the file's version property. 

As a feature request, have WinGet check the file's properties for version data when it's missing from the Windows Registry.

**Comment by krystofkrticka** [comment]
Yes, I also spotted this issue with multiple times with apps not only installed from steam but also other apps because developers haven't specified that installer should write version number to registry.
For example WinDirStat from non steam apps also has this issue, but from steam apps DisplayFusion is also pretty good example of app which has issue but that is because of steam and I see display fusion installed 2 times on my computer because steam just executes standard installer.

**Comment by d4kir92** [comment]
so it can work with every new launcher coming out, great
