### ISSUE TITLE
Should the package names include the version?

### ISSUE THREAD

**Issue by Teraskull** [microsoft/winget-pkgs#1111]
# Description of the new feature/enhancement

Should the package names include the version?

![image](https://user-images.githubusercontent.com/24798198/82853028-c874ba00-9f04-11ea-971f-789c129e0d97.png)

# Proposed technical implementation details (optional)

I think that the version column is enough.

**Comment by MarNicGit** [comment]
I don't think it should, simply because there's already a field for that.

**Comment by Teraskull** [comment]
> I don't think it should, simply because there's already a field for that.

Exactly, I will make a PR to remove versions from current package names.

**Comment by StefanKoell** [comment]
I'm the author of [Royal TS](https://github.com/microsoft/winget-pkgs/tree/master/manifests/RoyalApps/RoyalTS) and while I agree that the version should not be in the package name, it would be good to have at least an option to put the "major" version name in the package name somehow. The reason for that is, a new major version may require a new license key and users may not want to upgrade from an older major version to a newer major version using a package manager (automatically using a script) without getting a new license key first. In Chocolatey I maintain two packages at the moment: Royal TS V4 and Royal TS V5.

**Comment by MarNicGit** [comment]
@StefanKoell I suppose that makes sense, especially since upgrading between two major versions (to take an extreme example, MS Word '97 and MS Word 365) can break a lot of existing workflows.

This should be determined on a case by case basis where the major version has a direct impact on the functionality/licensing/compatibility of the software, because some publishers/developers treat majors differently from others.

**Comment by mimi89999** [comment]
I also think that for some apps it's important to distinguish mayor versions. GNU/Linux distros put it sometimes, especially for programming languages.
