### ISSUE TITLE
[Package Request]: Dolby Access

### ISSUE THREAD

**Issue by PixelcrafterEXE** [microsoft/winget-pkgs#113543]
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### What's the type of your software?

msix

### Please provide the following information

Download Page Url: https://apps.microsoft.com/store/detail/dolby-access/9N0866FS04W8
Publisher: [Dolby Laboratories](https://apps.microsoft.com/store/search?publisher=Dolby%20Laboratories)
Publisher Page: https://apps.microsoft.com/store/search?publisher=Dolby%20Laboratories
Package Page: https://apps.microsoft.com/store/detail/dolby-access/9N0866FS04W8
Package Name: Dolby Access
Description: Dolby Atmos Virtualization and Equalizer Platform
Package Version: 3.17.3011.0
Installer URL: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/2721547d-bd61-4fc6-aed4-26498df9c95c?P1=1690647843&P2=404&P3=2&P4=OU0AAfkq7Cnnt11PHO0VRHeK%2bjhe3akrbc2avCoBdIJz8bTLEDOLhmyC%2bG6bfCZjws%2fNf6VWQLNJbsTgu%2bqJjw%3d%3d
License: 
License Page:
Copyright:

**Comment by szhu25** [comment]
I think since Dolby Access is a Microsoft Store app, it should be deployed using the `-s msstore` switch?
Although I couldn't find the app when searching by name.
e.g. `winget search "Dolby" -s msstore` does not show Dolby Access app.

However, you can install it with `winget install "9N0866FS04W8" -s msstore`
