### ISSUE TITLE
[Update Request]: Dell Command | Update

### ISSUE THREAD

**Issue by mjr4077au** [microsoft/winget-pkgs#115475]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Dell.CommandUpdate

### Package Version

4.9.0

### Please describe the changes you would like to see

There is a new release (4.9.0) available.
Download Page Url: https://www.dell.com/support/home/en-au/drivers/driversdetails?driverid=30f6m

**Comment by HugLifeTiZ** [comment]
There's yet another update to this package; it has version 5.0.0 now.

**Comment by FaserF** [comment]
See https://github.com/microsoft/winget-pkgs/pull/122364 and https://github.com/microsoft/winget-pkgs/pull/122363

Unfortunatly we cannot update it until this has been implemented in winget: https://github.com/microsoft/winget-cli/issues/1417

**Comment by mjr4077au** [comment]
How did the packages make it in to begin with if the validation process fails due to non-Dell hardware? The packages should be dropped until they can be updated as older DCU versions are known to be vulnerable.

**Comment by FaserF** [comment]
The reason is simple: In earlier versions dell did not check if the manufacturer is Dell and the application installed fine. 
The package should not be dropped therefore.

**Comment by mjr4077au** [comment]
I really disagree to be honest... There's present vulnerabilities in versions prior to 4.9.0 that make it dangerous to use in production systems. https://www.dell.com/support/kbdoc/en-au/000213546/dsa-2023-170-dell-command-update

Someone needs to accept the PR for the new versions despite the validation error due to incompatible hardware, or drop the package. It's not acceptable that Microsoft's repository ships insecure and outdated versions that have been patched upstream.

**Comment by BiosPlus** [comment]
Does command update not have a built in self-updater? I was sure it did.

Getting a version installed and then running `dcu-cli.exe /applyUpdates` via whatever remote administrative tool is being employed should automatically handle it.

**Comment by mjr4077au** [comment]
I'm sorry man, but I see that as akin to installing Windows 11 21H2 and letting Windows Update get it up to 23H2. As with my last comment, 4.6.0 has known vulnerabilities and is not something I want on my systems for even a second.

I've seen packages that fail to build in the PR CI/CD pipeline get manually pushed, I don't know what the problem is for doing the same with these now-vulnerable Dell packages also.

**Comment by BiosPlus** [comment]
@stephengillie Just bringing your attention to this one and looking for your input.

TL:DR; 
Current versions available via winget didn't need Dell hardware to pass check, newer versions require hardware check, current versions are vulnerability ridden.

New versions (5.2.0) opened here #138818 and here #138817 are up to date, but won't pass validation due to hardware req on the validation worker (see: [#1417](https://github.com/microsoft/winget-cli/issues/1417)).

Any chance these two PRs can get a pass so that users can upgrade to a safe version, or should best practice be to remove current manifests from winget due to their security issues? Or additional option/route (maybe get manifest tested/verified by contributors with appropriate hardware/spec)?

**Comment by stephengillie** [comment]
Hi @BiosPlus,

The difficulty is that if we can't install these packages correctly, then we can't scan them correctly. Since the developer has added this requirement that effectively blocks our VMs from installing their product, we aren't able to validate new versions, and the best course of action is to remove their older software from the repo as well.

**Comment by thmeyer-msft** [comment]
Hi @stephengillie, 

so what would be the process to unlist a package, as we can't maintain this any longer?

**Comment by stephengillie** [comment]
7 PRs will need to be opened, to remove the old manifest files - one PR per set of (usually 3) manifest files. Versions: `4.6.0`, `4.5.0`, `4.4.0`, `4.3.0`, `4.2.1`, `4.1.0`, `2.4.0`

**Comment by mjr4077au** [comment]
Super curious how this finally got updated after months of issues, but thanks to everyone involved!

**Comment by BiosPlus** [comment]
@mjr4077au these flags would be why. 

```
InstallerSwitches:
  Silent: /passthrough /S /V/quiet /V/norestart
  SilentWithProgress: /passthrough /V/passive /V/norestart
  Interactive: /passthrough
  InstallLocation: /VDELL_COMMAND_UPDATE="<INSTALLPATH>"
  Log: /V"/log ""<LOGPATH>"""
  Custom: /VREMOVE="CLI" /VADDDEFAULT="ALL"
```
I can't see them documented anywhere, so I'm not above still giving the one finger salute to dell on this one.

**Comment by SpecterShell** [comment]
> @mjr4077au these flags would be why.
> 
> ```
> InstallerSwitches:
>   Silent: /passthrough /S /V/quiet /V/norestart
>   SilentWithProgress: /passthrough /V/passive /V/norestart
>   Interactive: /passthrough
>   InstallLocation: /VDELL_COMMAND_UPDATE="<INSTALLPATH>"
>   Log: /V"/log ""<LOGPATH>"""
>   Custom: /VREMOVE="CLI" /VADDDEFAULT="ALL"
> ```
> 
> I can't see them documented anywhere, so I'm not above still giving the one finger salute to dell on this one.

They can never be documented. It is kinda installer switches tricks.
