### ISSUE TITLE
Seperate python2 manifests from the python3 ones

### ISSUE THREAD

**Issue by ardenercelik** [microsoft/winget-pkgs#11979]
Currently python2 and python3 packages are located in the same folder. I would like to install the latest python2 release without specifying the version by typing "winget install python2" or "winget install python27"

**Comment by OfficialEsco** [comment]
I've been thinking about this for a few other apps too, technically the `PackageName` for a few Packages are like `Python 2.7.9 (x64)` and `Python 3.9.2 (x64)` therefore if we fix the PackageName for those programs you should theoretically be able to do `winget install "Python 2"` and it will install the latest version of `Python 2.*.*`

However as you can see there is another problem since the `x64` and `x86` version have 2 different `PackageNames`, so we would need 2 different manifest eitherway, BUT ALSO this would bring more issues to the PR submissions where bots don't check for `PackageName` and people JUST update the `InstallerURL`, `Hash` and `Version`...

Yes its possible but the PR submissions would have to be stricter 🙄

**Comment by jedieaston** [comment]
> However as you can see there is another problem since the `x64` and `x86` version have 2 different `PackageNames`

Someone (I can do it unless someone gets to it before me) needs to go through and remove the architectures from the `PackageName`, since I added x86 architectures to all of the Python manifests a while ago and didn't realize that was there. Oops.

But we can move the Python2 ones to Python.Python.2 and the Python3 ones to Python.Python.3 (or keep them in Python.Python, since Python2 is EOL and people need to start their migrations... ;D). That's what I did for OpenJDK, and it works quite well.

Anyone have a preference?

**Comment by denelon** [comment]
There are several opinions about versioning and programming languages. Now that we have solid support for multi-architecture manifests, it is possible to merge packages with the same version into a single logical package. As the Windows Package Manager doesn't support pinning for versions yet, it seems logical to have different packages for different versions. Once we have pinning it would be possible to collapse again into a single package. I'd say it's more of a community preference.

This might be a great area for a discussion.

**Comment by jedieaston** [comment]
> This might be a great area for a discussion.

Yes please.
