### ISSUE TITLE
[Package Request]: Windows® 10 and Windows 11* Wi-Fi Drivers for Intel® Wireless Adapters

### ISSUE THREAD

**Issue by jinyuzu99** [microsoft/winget-pkgs#119813]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.intel.com/content/www/us/en/download/19351/windows-10-and-windows-11-wi-fi-drivers-for-intel-wireless-adapters.html
Publisher: Intel
Package Name: Windows® 10 and Windows 11* Wi-Fi Drivers for Intel® Wireless Adapters
Description: This download record installs the Windows® 10 and Windows 11* WiFi package drivers 22.240.0 for the Intel® Wi-Fi 6E/Wi-Fi 6 and Intel® 9000 series Wireless Adapters.
Package Version: 22.240.0
Installer URL: https://downloadmirror.intel.com/784628/WiFi-22.240.0-Driver64-Win10-Win11.exe

**Comment by drshtmstry** [comment]
https://github.com/microsoft/winget-pkgs/pull/123321
Already created PR but installer doesn't support silent mode. or maybe I don't have enough knowledge.

**Comment by Eddga** [comment]
I've made a PR for it #132908
But in my mind this is also partially bIocked by #1417 
The Intel WiFi Driver installer seems to exit without error even when no proper hardware was found. And maybe that's ok because in the end that's Intel's design decision.
But it would be better if one could set some hardware requirements for this. In my mind winget should throw an error when trying to install this on a system without an Intel WiFi card.
Anyway let's see if the validation checks find any issues with it.
