### ISSUE TITLE
[Update Request]: MillerPuckette.PureData 0.54.0

### ISSUE THREAD

**Issue by luzpaz** [microsoft/winget-pkgs#123600]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

MillerPuckette.PureData

### Package Version

0.54.0

### Please describe the changes you would like to see

https://puredata.info/downloads/pure-data/releases/0.54-0

**Comment by Dragon1573** [comment]
@luzpaz There maybe some problem for version `0.54.0` with unattended installation. Except mine, there are other 4 pull requests and all of them meet the same problem.

- https://github.com/microsoft/winget-pkgs/pull/111275
- https://github.com/microsoft/winget-pkgs/pull/111276
- https://github.com/microsoft/winget-pkgs/pull/111566
- https://github.com/microsoft/winget-pkgs/pull/123601

**Comment by luzpaz** [comment]
That's weird, I didn't see those PRs when I made the search. Apologies.

**Comment by BrandonWanHuanSheng** [comment]
Yes, it is true. That silent switch is not working on exe.

**Comment by Dragon1573** [comment]
@BrandonWanHuanSheng - Is it able to open an issue for PureData and ask publisher/author if the installer supports silent installation?

**Comment by BrandonWanHuanSheng** [comment]
I am still in the PR.

**Comment by BrandonWanHuanSheng** [comment]
> @BrandonWanHuanSheng - Is it able to open an issue for PureData and ask publisher/author if the installer supports silent installation?

Yes. But need to wait for sometimes. Pull request will restart one time after we know the SHA256

**Comment by Lucarda** [comment]
Hi all,

yes `0.54-0` had a problem with the `/s` switch but this was fixed by me in `0.54-1`.

now I'm confused on `0.54-1` since i made a PR and i got a failing installer validation. but @BrandonWanHuanSheng made another PR with the same installer that passes the validation.

for now I'm going to draft my PR and wait to see what happens with https://github.com/microsoft/winget-pkgs/pull/123781

@luzpaz `0.54-0` won't get fixed so we can probably close this issue.
