### ISSUE TITLE
[Update Request]: Change Tableau.TableauPrepBuilder to Tableau.PrepBuilder

### ISSUE THREAD

**Issue by dobsontxx** [microsoft/winget-pkgs#126959]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Tableau.TableauPrepBuilder

### Package Version

23.3.30378

### Please describe the changes you would like to see

Want to change package identifier from Tableau.TableauPrepBuilder to Tableau.PrepBuilder to follow convention of other Tableau products. 

Any way I can do this?

Thanks.

**Comment by dobsontxx** [comment]
Hi @BrandonWanHuanSheng, thanks for spotting this! I've fixed this in PR #127091.

**Comment by Dragon1573** [comment]
Issue can be closed as completed.

- Resolved by https://github.com/microsoft/winget-pkgs/pull/126957
- Resolved by https://github.com/microsoft/winget-pkgs/pull/127103

**Comment by mdanish-kh** [comment]
@dobsontxx To change PackageId, you need two separate PRs, one for deleting a version from the old PackageId (`Tableau.TableauPrepBuilder` in this case) and the other for adding it under new location (`Tableau.PrepBuilder` in this case) for every version of the package. Since we only have a single version  of this package (i.e. [23.3.30378](https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/Tableau/TableauPrepBuilder/23.3.30378)), this change should require 2 PRs in total.

**Comment by dobsontxx** [comment]
@mdasnish-kh Appreciate for your reply. Will make these two PRs. Thanks.

**Comment by dobsontxx** [comment]
@mdasnish-kh Appreciate for your reply. Will make these two PRs. Thanks.

**Comment by dobsontxx** [comment]
@mdasnish-kh Appreciate for your reply. Will make these two PRs. Thanks.

**Comment by dobsontxx** [comment]
@mdanish-kh Appreciate for your reply. Will make these two PRs. Thanks.
