### ISSUE TITLE
[Package Request]: WinAuth

### ISSUE THREAD

**Issue by phpcitizen** [microsoft/winget-pkgs#128664]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url:https://winauth.github.io/winauth/download.html
Publisher:winauth
Package Name:WinAuth 
Description:Portable open-source Authenticator for Windows
Package Version:3.5
Installer URL:https://github.com/winauth/winauth/releases/download/3.5.1/WinAuth-3.5.1.zip

**Comment by R-Adrian** [comment]
i'm against adding obsolete software to the winget package manifest repository.

Winauth looks abandoned, most recent "stable" release is from 2017 and the repository was frozen / archived in january 2019. https://github.com/winauth/winauth

Also, in my opinion this app is not much of a 2-factor auth if the 'secret' key factor for OTP generation lives on the same computer/device that also has the primary credentials saved.
If the computer is compromised then the key seeds for the 2FA will most likely also be compromised at the same time.

I think that this app transforms 2FA OTP keys into being just a placebo and actually not more secure than password-only authentication... probably even worse since it gives a false sense of security. This is basically keeping all eggs in the same basket.

**Comment by stephengillie** [comment]
There have been several major CVEs since 2017. Does this software present any exploits? If so, it might be a Potentially Unwanted Application.
