### ISSUE TITLE
[Package Issue]: FireDaemon.OpenSSL - installation directory not added to path

### ISSUE THREAD

**Issue by janegilring** [microsoft/winget-pkgs#130257]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The folder `C:\Program Files\FireDaemon OpenSSL 3\bin` is not added the the system path after installation.

### Steps to reproduce

1. `winget install FireDaemon.OpenSSL`
2. Open new console session
3. Run `openssl version`

### Actual behavior

```
openssl version
openssl: The term openssl is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Expected behavior

```
openssl version
OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)
```

### Environment

```raw
winget --info
Windows Package Manager v1.6.3133
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Server v10.0.20348.2113
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3133.0
```

**Comment by Trenly** [comment]
This seems to be an installer issue. Because FireDaemon-OpenSSL uses an exe installer, WinGet has very limited control over what happens. In effect, all WinGet does is run the installer with the switches - `./FireDaemon-OpenSSL-x64-3.1.4.exe /exenoui /qn /norestart REBOOT=ReallySuppress`. 

You can verify the same behavior occurs if you download the installer from FireDaemon and run it directly; Even after a manual install and starting a new terminal session, the directory has not been added to path.

Unless there is an installer switch for adding the directory to path, there really isn't anything WinGet can do to fix this.

**Comment by janegilring** [comment]
Thanks for the quick reply.

I could not find any related options for this in version 3.1.4, however - I found this for the newer 3.2.0 version:
![image](https://github.com/microsoft/winget-pkgs/assets/2039662/340b69df-c53b-4d23-8111-7b5aad7b8ebd)

I does not seem to be any installer switches available, though:
![image](https://github.com/microsoft/winget-pkgs/assets/2039662/ede34452-abd9-4c57-93bc-2d5b2048f00b)

**Comment by firedaemon-cto** [comment]
Hi @janegilring,
It's nice to see others using and integrating the OpenSSL binaries and installer provided by us (FireDaemon Technologies Limited)!

The executable installer is a bootstrapper created with Advanced Installer. But Windows Installer generally does not provide a way to view public installer properties, so you would either have to query the msi file or - much better of course - rely on a vendor's useful documentation.

You are correct to note that the ability to set the system environment is a recent addition and has been available since the last installer for the latest version of OpenSSL 3.2.0.

You can set the following public installer properties by passing them on the command line:

- ```APPDIR="<folder>"``` optionally change the installation folder (default _%PROGRAMFILES%\FireDaemon OpenSSL 3_)
- ```ADJUSTSYSTEMPATHENV=yes``` optionally prepend the _APPDIR\bin_ folder to the System environment.

This works regardless of whether the installation is performed silently or with a user interface.

E.g.
```
FireDaemon-OpenSSL-x64-3.2.0.exe ADJUSTSYSTEMPATHENV=yes "APPDIR=C:\Program Files\FireDaemon OpenSSL 3" /exenoui /qn
```

We will update our documentation accordingly.

**Comment by janegilring** [comment]
@firedaemon-cto Excellent, thanks a lot for the information Klaus.
