### ISSUE TITLE
Chrome Installer hash mismatch

### ISSUE THREAD

**Issue by BeLeap** [microsoft/winget-pkgs#1305]
![image](https://user-images.githubusercontent.com/46488521/83227471-3ea44580-a1bf-11ea-9a1b-d3b23af7c0a5.png)
On Windows 10, 2004 with Powershell 7.0.1

**Comment by mciancia** [comment]
I had the same issue, there is PR open for this (https://github.com/microsoft/winget-pkgs/pull/1254), though it will brake on next release of chrome since url in manifest does not specify version, we always get the latest one.

**Comment by SoftCreatR** [comment]
Well, if PRs would be merged faster, this wouldn't be an issue as we (me and my team) are pulling new versions for multiple applications and push them as soon as they're available (nearly realtime). However, that won't help as long as it takes 2 or more days, before a PR get's merged (if it get's merged).

**Comment by dmex** [comment]
I have a PR for the latest Chrome: https://github.com/microsoft/winget-pkgs/pull/1035

It's on hold waiting for feedback from the winget team. It's configured for per-machine installation rather than the insecure per-user installation but the per-machine validation failed manual review and I asked for guidance about switching to per-user but there has been no response from the winget team :/

**Comment by denelon** [comment]
#1254 was merged for Chrome.
