### ISSUE TITLE
ASIO4ALL flagging my antivirus??

### ISSUE THREAD

**Issue by bweezy320** [microsoft/winget-pkgs#135716]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

When ASIO4ALL tries to update, saying hashed don't match, but also my antivirus detects a trojan, in the outbound connection to cybersoft.ru

### Steps to reproduce

Try to update ASIO4ALL

### Actual behavior

Doesn't update. AV is flagged.

### Expected behavior

It should update 

### Environment

```raw
Hdh
```

### Screenshots and Logs

![IMG_20240122_044440863](https://github.com/microsoft/winget-pkgs/assets/46215019/653e2260-a719-4420-8fad-6972d625631a)

**Comment by Trenly** [comment]
@stephengillie - is this really a Validation-Defender-Error, or is this more of an `Area-External`? It seems Malwarebytes is the one doing the flagging

**Comment by Exorcism0666** [comment]
https://www.virustotal.com/gui/file/5fc936fcde5552662ffb3b14f84ab8f1f6a2558270010b141d3453977b79e97b

**Comment by bweezy320** [comment]
Forgive me, I'm not a dev, just a guy with a computer, so I have NO idea
what any of that means. Don't know if it's a false positive but just wanted
to report just in case.

**Comment by BinToss** [comment]
The SHA256 in https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/MichaelTippach/ASIO4ALL/2.15/MichaelTippach.ASIO4ALL.installer.yaml is outdated or incorrect. The hash of `ASIO4ALL_2_15_English.exe` at https://www.asio4all.org/downloads_11/ASIO4ALL_2_15_English.exe is `b22282d5a2daa646deb624cf461bf4f1dfeda541cc505a6781124275f8c2960d`.

----

Correlation =/= causation

The AV issue isn't caused by WinGet nor ASIO4ALL. It's the `cybersoft.ru` ([WHOIS](https://www.whois.com/whois/cybersoft.ru)) domain—which is completely unrelated. WinGet, the package for ASIO4ALL, and ASIO4ALL itself make no connections to that domain, so **other software on your PC is connecting to Cybersoft.ru**.

suggestion:
1. Run `notepad` as admin
2. In the Open File dialog, paste `%SystemRoot%\system32\drivers\etc\HOSTS` and press Enter
3. At the bottom of the file, add `0.0.0.0 cybersoft.ru` and save changes. This will cause all outgoing connections to that domain to fail.

This is a bandaid fix. You should first check if Malwarebytes logged which application attempted the connection. If it did not (I'm 60% sure it does), then I recommend searching for and installing software that logs network connections, allowing you to determine which software is attempting to connect to the domain. I'm biased towards NetLimiter.

**Comment by bweezy320** [comment]
Ok, thanks for the response. That's strange because it only happens when
that package attempts to update in Winget UI.

Also thank you for the suggestion to block the website mentioned.

Cheers.

Bryan

**Comment by bweezy320** [comment]
Ok thank you. Will do that
