### ISSUE TITLE
[Update Request]: TortoiseSVN

### ISSUE THREAD

**Issue by Regtur1983** [microsoft/winget-pkgs#149673]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TortoiseSVN.TortoiseSVN

### Package Version

1.14.7

### Please describe the changes you would like to see

There is a new version (1.14.7) available.

Downloadlink: https://tortoisesvn.net/downloads.html

**Comment by Regtur1983** [comment]
Double request. This one can be closed.

**Comment by vikingnope** [comment]
@Regtur1983, it should be fixed but I think there is another issue

@stephengillie would the two package version in the following screenshot override the latest update since they are a bigger number? ([1.14.29387](https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/TortoiseSVN/TortoiseSVN/1.14.29387), [1.14.29465](https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/TortoiseSVN/TortoiseSVN/1.14.29465)) 

![image](https://github.com/microsoft/winget-pkgs/assets/81376423/04b01812-d40e-4c9d-b44b-bb2291494ef3)

**Comment by vikingnope** [comment]
@stephengillie already did pull requests just in case

**Comment by vikingnope** [comment]
@Regtur1983, this issue has been successfully resolved, kindly close this ticket as complete please.

![image](https://github.com/microsoft/winget-pkgs/assets/81376423/7d7259f4-cd67-46c0-8ff5-a3b300282860)
