### ISSUE TITLE
discord was submited as a neutral architecture and not as a x86 architecture

### ISSUE THREAD

**Issue by EliasGabr** [microsoft/winget-pkgs#15235]

**Comment by ItzLevvie** [comment]
I think changing the architecture to x86 will rule out the arm64 architecture because `DiscordSetup.exe` is x86; but I don't have an arm64 device on hand from Microsoft so I can't test it.

An arm64 device, such as Surface Pro X, can only run arm64 and x86 installers at the moment, and support for x64 installers are only available from Windows Insider Preview's Dev Channel builds.

**Comment by jedieaston** [comment]
@ItzLevvie, winget automatically selects the architecture: x86 installer on arm64 if a native installer (or neutral installer, which is native) is unavailable.

For example, git:

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/21368066/120321948-e3b19c80-c2b1-11eb-847d-509715d6a720.png">
