### ISSUE TITLE
Winget installs zoom's installs through .msi package 

### ISSUE THREAD

**Issue by Manas2006m7** [microsoft/winget-pkgs#15419]
Hello,
Just a few minutes ago i installed _zoom meetings_ (zoom.zoom) via WinGet , instead of installing through .exe , it installed through _.msi_ , which increased the application size to 148MB , whereas , the .exe version from their website (zoom.us) is 9.6MB , NOTE: application size is measured in control panel/programs . I hope , _.msi_ version would be replaced with .exe version of the corresponding application. 

Thanks and regards,
Manas

**Comment by lychichem** [comment]
Feel free to just edit the download link in manifest.

**Comment by jedieaston** [comment]
The full installer is used because it installs for all users, and has more metadata for winget to work with. The smaller installer still ends up being the same size, it just doesn't report all of the files to the add/remove programs table. It probably doesn't matter which one we ship (although we should also add the exe installer since it doesn't require admin rights IIRC).

**Comment by OfficialEsco** [comment]
Did a little digging, found only the x64 installer tho, but the links are `https://cdn.zoom.us/prod/5.6.6.961/x64/ZoomInstallerFull.exe` (installs for user) and `https://cdn.zoom.us/prod/5.6.6.961/x64/ZoomInstaller.exe` 
Zoom claims to be 9.77 MB in Revo Uninstall but the actual folder is 143 MB
![image](https://user-images.githubusercontent.com/15158490/120325931-72411080-c2e8-11eb-92f8-81ba4fe90f29.png)

And yeah i agree we should add the exe for `InstallerScope: User` compatibility, however the exe version is `5.6.6 (961)` which might cause issues?
