### ISSUE TITLE
Oracle Virtualbox 6.1.22 upgrade error

### ISSUE THREAD

**Issue by Teraskull** [microsoft/winget-pkgs#15504]
# Brief description of your issue

I currently have version `6.1.16` installed. If I run `winget upgrade Oracle.VirtualBox`, it says `No applicable update found.`, even though the manifest for version `6.1.22` exists.

# Steps to reproduce
1. Have a version of Virtualbox lower than `6.1.22` installed, in my case it's `6.1.16`.
2. Run `winget upgrade Oracle.VirtualBox`.

# Expected behavior
Successfully download and install new version.

# Actual behavior
`No applicable update found.` message.

# Environment

```none
Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.1023
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

```

**Comment by denelon** [comment]
@Teraskull this is likely due to either the name or version in the manifest(s) and how the package is reported by Add/Remove programs when it is installed. I moved the issue to the pkgs repository to see if anyone here has the knowledge to properly adjust the manifest for better matching with the "List" command. The "List" command is where the logic exists to map between package manifests and installed Apps.

**Comment by leochras** [comment]
Same problem with newer version..
![image](https://user-images.githubusercontent.com/16163571/127817975-b4f7fa6e-e2a0-44bb-ab4a-fd0b4042fe92.png)

**Comment by denelon** [comment]
Several new versions have been released:

https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/Oracle/VirtualBox

Is this still happening?

**Comment by leochras** [comment]
idk I'm not using windos anymore
