### ISSUE TITLE
[Package Request]: MSHV

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/winget-pkgs#157583]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://sourceforge.net/projects/mshv/files/
Publisher: Christo LZ2HV
Package Name: MSHV
Description: MSHV Amateur Radio Software.
Package Version: 2.74
Installer URL: https://sourceforge.net/projects/mshv/files/MSHV_274_Installer_32_and_64bit.exe

**Comment by Dragon1573** [comment]
@AsciiWolf - This issue should be closed as not planned, since there's a https://github.com/microsoft/winget-pkgs/labels/Hardware problem with the package.

See following contents for more details:

- https://github.com/microsoft/winget-pkgs/pull/157837#issuecomment-2169097144
- https://github.com/microsoft/winget-pkgs/pull/157837#issuecomment-2174222090

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

**Comment by AsciiWolf** [comment]
@Dragon1573 Please re-try with the newest installer:

https://sourceforge.net/projects/mshv/files/MSHV_2766_Installer_32_and_64bit.exe

Thanks! :)
