### ISSUE TITLE
[Package Request]: Grist Electron Application

### ISSUE THREAD

**Issue by Jakopt** [microsoft/winget-pkgs#159477]
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/gristlabs/grist-desktop/releases
Publisher: Grist Labs Inc.
Package Name: grist-desktop
Description: Grist for desktop allows easy editing of Grist spreadsheets independent from a server.
Package Version: 0.2.9
Installer URL: https://github.com/gristlabs/grist-desktop/releases/download/v0.2.9/grist-electron-windows-0.2.9-x64.exe

**Comment by Dragon1573** [comment]
Hello @gristlabs,

Since this package is compiled in **GitHub Actions** and released in **GitHub Releases**. Would you consider taking full control of your package and integrate [WinGet Releaser v2](https://github.com/marketplace/actions/winget-releaser) to your workflow configurations? This can automatically trigger a manifest submission once new version is released, making manifests in WinGet always up to date.

The "very first" manifest should be manually submitted (as in #159490). After it is available, _WinGet Releaser v2_ will also be available to use. ❤️
