### ISSUE TITLE
[Update Request]: ViGEm.HidHide 1.5.230

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#160054]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

1.5.230

### Package Version

1.5.230

### Please describe the changes you would like to see

https://github.com/nefarius/HidHide/releases/tag/v1.5.230.0

**Comment by alyssadev** [comment]
The software developer has indicated that a new package identifier `neferius.HidHide` should be used instead due to trademark concerns with "ViGEm". Not sure what impact this would have on this update request. Perhaps 1.5.230 can be merged, then when deprecating packages is finally supported (!) this can be marked as such.

Related:
https://github.com/microsoft/winget-cli/issues/4344

**Comment by stephengillie** [comment]
I believe all that might be required is to move the manifests. 2 PRs would be needed foreach manifest version:
- Removal PR to remove the version from `ViGEm.HidHide`.
- Addition PR to re-add the version under `neferius.HidHide`.

**Comment by masterflitzer** [comment]
already closed without changing package identifier as mentioned? is this still wanted? if nobody is has started yet i'd volunteer
