### ISSUE TITLE
[Update Request]: fzf v0.54.0 -> 0.54.0

### ISSUE THREAD

**Issue by junegunn** [microsoft/winget-pkgs#163342]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

junegunn.fzf

### Package Version

v0.54.0 -> 0.54.0

### Please describe the changes you would like to see

Would it be possible to change the fzf version `v0.54.0` to `0.54.0`, or add `0.54.0` in addition to `v0.54.0`?

### Why?

fzf [changed its tagging strategy in 0.54.0 to have `v` prefix](https://github.com/junegunn/fzf/commit/9e92b6f11e0f59272de410f56493893334071e6e) (i.e. `0.53.0` -> `v0.54.0`), but [the WinGet release workflow](https://github.com/junegunn/fzf/blob/9e92b6f11e0f59272de410f56493893334071e6e/.github/workflows/winget.yml#L13) was not updated to remove it, so a WinGet package with `v` prefix in its version was [released](https://github.com/microsoft/winget-pkgs/pull/161945). Unfortunately, this sudden change in version scheme is reported to disturb upgrading. e.g. https://github.com/junegunn/fzf/issues/3927

**Comment by Trenly** [comment]
@junegunn - out of curiosity, would you be able to see if the same behavior occurs using the [1.9.1792-preview client](https://github.com/microsoft/winget-cli/releases/tag/v1.9.1792-preview) ? You may have to downgrade back to `fzf 0.53.0` in order to check

We will certainly update the manifest here to remove the `v`, but I'm hopeful that future versions of the client will handle it without issue

**Comment by junegunn** [comment]
Thanks for the quick turnaround! I'll test the preview client when I get a chance, I'll also pass it on to the reporter of the issue.
