### ISSUE TITLE
Some issues have been resolved but not closed.

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#163332]
e.g.
#161389 → Resolve in Pull Request #161423
#162364 → Resolve in Pull Request #159064
#162370 → Already exist

It seems due the pipeline pause.

**Comment by Trenly** [comment]
This is because in the Pull Request the "Resolves" keyword or "Closes" keyword was not used.  Simply mentioning the issue in the PR will not link it to the issue. Take a look at this page for how to link issues to pull requests -  https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword 

It is important to note that only the initial post on a PR can be used for linking - posting in a comment won't cause the link to occur.

Sometimes the PR is opened before the issue even exists, as was the case with your second example (#162364 / #159064) which means that the PR author couldn't have linked it. Additionally, not all authors search for open issues when creating PRs, which means that a moderator has to manually go in and close the issue.

**Comment by Trenly** [comment]
The issues mentioned in the initial post on this issue have now been closed.

**Comment by DuckDuckStudio** [comment]
Moderators can try to manually link issue when reviewing.
