### ISSUE TITLE
[Update Request]: Update Required for `glzr-io.glazewm` Package Update

### ISSUE THREAD

**Issue by mfaathirarsa** [microsoft/winget-pkgs#167162]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

glzr-io.glazewm

### Package Version

3.1.1

### Please describe the changes you would like to see

It appears that the `glzr-io.glazewm` package has recently changed its installation method. Previously, it was distributed as a portable application, but it now uses an installer that sets up both Glazewm and Zebar.

**Details:**

- **Old Installation Type:** Portable
- **New Installation Type:** Installer
  - **Glazewm Repository:** https://github.com/glzr-io/glazewm
  - **Zebar Repository:** https://github.com/glzr-io/zebar

**Impact:**

This change may affect users who are relying on the portable version of the package. The package metadata and installation scripts may need updating to reflect the new installer method and to ensure proper installation and configuration.

**Comment by Dragon1573** [comment]
@mfaathirarsa, do you open the issue with a wrong version number?

Release [`v2.1.1`](https://github.com/glzr-io/glazewm/releases/tag/v2.1.1) was released at Jan 25, 2024. Since manifest was submitted Jan 26 by @Trenly in #136351, assets of that release haven't changed.

The latest version of `glazewm` at the moment is [`v3.1.1`](https://github.com/glzr-io/glazewm/releases/tag/v3.1.1). Maybe this should be an "update request" of new version?

**Comment by mfaathirarsa** [comment]
Okay I'll edit accordingly
