### ISSUE TITLE
[Package Request]: DOSimple

### ISSUE THREAD

**Issue by msuru-coder-notgamer** [microsoft/winget-pkgs#167690]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/msuru-coder-notgamer/DOSimple/releases/tag/v1.3.3
Publisher: msuru-coder-notgamer
Package Name:DOSimple 1.3.3
Description: https://github.com/msuru-coder-notgamer/DOSimple/blob/main/README.md
Package Version:1.3.3
Installer URL:https://github.com/msuru-coder-notgamer/DOSimple/releases/download/v1.3.3/DOSimple.Installer.exe

**Comment by Dragon1573** [comment]
Hi @msuru-coder-notgamer 👋🏼

Since you are the publisher & author of this package, it would be better authoring and submitting manifests by yourself. Also it's nice if you can integrate [WinGet Releaser](https://github.com/marketplace/actions/winget-releaser) into your GitHub Workflows. When you create a new release, a related PR will automatically submit to this repository for announcing newer versions.

**Comment by msuru-coder-notgamer** [comment]
I added installer link. Here: https://github.com/msuru-coder-notgamer/DOSimple/releases/download/v1.3.3/DOSimple.Installer.exe

**Comment by znarfm** [comment]
Tried to use [this](https://github.com/msuru-coder-notgamer/DOSimple/releases/download/v1.3.3/DOSimple.Installer.exe) link. However it still is not supported via winget as said by the bot above: 

> This package appears to depend on .dlls that aren't available via symlink.

Tested it on my machine and winget was able to install the files however, it does not create any entries in the App list in Windows Settings, Start Menu, and even a command in the terminal.
