### ISSUE TITLE
[Update Request]: AlDanial.Cloc to version 2.02 (currently 2.00)

### ISSUE THREAD

**Issue by AlDanial** [microsoft/winget-pkgs#168649]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

AlDanial.Cloc

### Package Version

2.02

### Please describe the changes you would like to see

cloc version 2.02 is available at https://github.com/AlDanial/cloc/releases

**Comment by Dragon1573** [comment]
@AlDanial 👋🏼 Sorry to ping you here.

Since you're the package publisher & author of this package, could you please explain how you create new releases? I'd appreciate if you can integrate the compilation and releasing of this package, and take full control of further manifests using _WinGet Releaser_. This can speed up code review of those pull requests.

**Comment by AlDanial** [comment]
@Dragon1573 : thanks for taking care of this for me!  To answer your question, I prepare releases manually, nominally twice a year.  Next release I'll create the PR here for it.

On a related note, two cloc users report problems with the cloc winget packages: https://github.com/AlDanial/cloc/issues/849.
