### ISSUE TITLE
[Package Issue]: Logitech.OptionsPlus

### ISSUE THREAD

**Issue by jay-babu** [microsoft/winget-pkgs#172867]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

https://github.com/microsoft/winget-pkgs/issues/172095

### Steps to reproduce

https://github.com/microsoft/winget-pkgs/issues/172095

### Actual behavior

https://github.com/microsoft/winget-pkgs/issues/172095

### Expected behavior

https://github.com/microsoft/winget-pkgs/issues/172095

### Environment

```raw
https://github.com/microsoft/winget-pkgs/issues/172095
```

**Comment by aisgbnok** [comment]
> @aisgbnok this is still happening

_Originally posted by @jay-babu in https://github.com/microsoft/winget-pkgs/issues/172095#issuecomment-2344330326_

The hash mismatch is due to Logitech releasing a new version of Options+ today. Winget uses a vanity URL for Options+ that always points to the latest version, causing the hash to sometimes be outdated. Winget requires the hash to be manually updated by the community.

The hash will be updated in:

- Closed by #172852

---

Unfortunately, there will always be a delay between Logitech releasing a new version with a new hash and Winget being updated with the new hash. Unless a static URL is found for per-version installs, which I don't believe Logitech provides for this software. Except then the trade-off would be installing an older version until the new version is added to Winget.
