### ISSUE TITLE
[Update Request]: Synology Drive Client to version 3.5.1-16101

### ISSUE THREAD

**Issue by Aocro** [microsoft/winget-pkgs#179537]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Synology.DriveClient

### Package Version

3.5.1-16101

### Please describe the changes you would like to see

- [Synology Drive Client-3.5.1-16101-x64.msi](https://global.synologydownload.com/download/Utility/SynologyDriveClient/3.5.1-16101/Windows/Installer/x86_64/Synology%20Drive%20Client-3.5.1-16101-x64.msi)
- MD5: `b453aedd6a5597546e9b6bb9ab64061e`
- [Release notes](https://www.synology.com/de-de/releaseNote/SynologyDriveClient)

Thanks!

**Comment by DeepK7** [comment]
Why is this showing as version **7.5.1.16101** ? the version number is **3.5.1.116101**. 

Somewhere the **3** has been transposed for a **7**.

This shows up in Windows "Apps" and "Programs and Features" now as version 7.5.1.16101 instead of correctly showing as version 3.5.1.116101

This needs fixing.

**Comment by Dragon1573** [comment]
> Why is this showing as version **7.5.1.16101** ? the version number is **3.5.1.16101**. 

**Add & Remove Programs** are written by the MSI installer itself. Could you please try manually install the MSI file tp see if it matches 7 instead of 3?
