### ISSUE TITLE
all packages available in vcpkg.

### ISSUE THREAD

**Issue by cjwijtmans** [microsoft/winget-pkgs#18107]
As i am looking through packages now this isnt a package manager but a glorified app store on the command line. Very dissapointing.

**Comment by jedieaston** [comment]
This has already been covered ad nauseum in the microsoft/winget-cli discussions section.

**Comment by cjwijtmans** [comment]
Feel free to link it then.

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-cli/discussions/223 there ya go lill bud

**Comment by cjwijtmans** [comment]
Nowhere is vcpkg mentioned so? But first of all dont be condescending"lil bud".

**Comment by ItzLevvie** [comment]
It doesn't have to be mentioned; most (if not all) of the discussion in https://github.com/microsoft/winget-cli/discussions/223 are talking about how superior other package managers are in terms of functionality + more compared to the Windows Package Manager, and the Windows Package Manager team is aware of it and how it can be improved, etc.

**Comment by cjwijtmans** [comment]
> It doesn't have to be mentioned; most (if not all) of the discussion in [microsoft/winget-cli#223](https://github.com/microsoft/winget-cli/discussions/223) are talking about how superior other package managers are in terms of functionality + more compared to the Windows Package Manager, and the Windows Package Manager team is aware of it and how can it be improved, etc.

To discuss how "superior" other package managers are, first winget has to be a package manager, which it is demonstrably not. Neither did i start a discussion of how "superior other package managers" are. But i do see some microsoft employees egos are easily shattered by stating a simple fact, probably because they dont know what a package manager is. Which is hilarious as vcpkg is a "microsoft" product. Amusing replies to an issues to make this an actual package manager by using vcpkg, another microsoft product.

**Comment by OfficialEsco** [comment]
vcpkg is mentioned multiple times in that thread tho... Your title claims all the packages are available in vcpkg, meanwhile your comment(s) says this is not a real package manager which is the whole point of that thread.
And i don't see any Microsoft Employees defending their Package Manager? 🤷‍♂️

**Comment by cjwijtmans** [comment]
> Your title claims all the packages are available in vcpkg
It says "all packages available in" Not "All packages ARE available in" 

Aparently microsoft employees cant read either. 

> And i don't see any Microsoft Employees defending their Package Manager? 🤷‍♂️

No? What are these passive aggressive replies to stating the simple fact that this is not a package manager and it needs to look at vcpkg, a microsoft product? This product was advertised on the microsoft website as a package manager.

**Comment by ItzLevvie** [comment]
> Neither did i start a discussion of how "superior other package managers" are.

My point being is why you created this issue rather than continuing the discussion in https://github.com/microsoft/winget-cli/discussions/223 is beyond me; and first - let me remind you of the [Code of Conduct](https://opensource.microsoft.com/codeofconduct/) that applies to all of Microsoft's repositories before this issue ends up locked or closed.

> It says "all packages available in" Not "All packages ARE available in"

The piece of text you've written in the title is a common language error; `are` is plural and goes with packages, not the other way around.

> But i do see some microsoft employees egos are easily shattered by stating a simple fact, probably because they dont know what a package manager is.

We're Community Moderators; and for you to call us (or anyone else engaging in this conversation) `microsoft employees egos` or `microsoft employees cant read either` is quite disrespectful and doesn't contribute any usefulness to this conversation other than stirring up a heated discussion.

I would advise you to cease any sort of communication here and contribute something useful in https://github.com/microsoft/winget-cli/discussions/223 instead. That's where most of this discussion is happening, and not on the issue tracker.

**Comment by cjwijtmans** [comment]
> My point being is why you created this issue rather than continuing the discussion in [microsoft/winget-cli#223](https://github.com/microsoft/winget-cli/discussions/223) is beyond me; and first - let me remind you of the [Code of Conduct](https://opensource.microsoft.com/codeofconduct/) that applies to all of Microsoft's repositories before this issue ends up locked or closed.

Because i am talking about adding vcpkg packages? 

> The specific piece of text you've written in the title is a common language error; `are` is plural and goes with packages, not the other way around.

Please go back to school.

> We're Community Moderators; and for you to call us (or anyone else engaging in this conversation) `microsoft employees egos` or `microsoft employees cant read either` is quite disrespectful and doesn't contribute any usefulness to this conversation other than stirring up a heated discussion between individuals that don't want to be involved.

Your replies were disrespectful, so you get disrespect back, that is how it works. I merely replied to you.

> I would advise you to cease any sort of communication here and contribute something useful in [microsoft/winget-cli#223](https://github.com/microsoft/winget-cli/discussions/223) instead. That's actually where most of this discussion is happening, and not on the issue tracker.

Again that topic is not talking about adding vcpkg packages.

**Comment by ItzLevvie** [comment]
> Because i am talking about adding vcpkg packages?
> Again that topic is not talking about adding vcpkg packages. 

"As i am looking through packages now this isnt a package manager but a glorified app store on the command line. Very dissapointing." - so then - does this statement that you wrote look like "adding vcpkg's packages to the winget-pkgs repository" to you? No, it doesn't seem like it to me and others - please be elaborate on what you're talking about and the point you're making here. 

You're seemly being against your initial point here; and starting up or moving to another conversation that isn't related to what you've wrote when you first created this issue. 

Please either choose one: are you suggesting that the Windows Package Manager isn't a package manager or do you want to add vcpkg packages to the Windows Package Manager catalog? 

You created this issue to stir up a conversation about how Windows Package Manager isn't a package manager; and I agree about that (and no where did anyone say that they were going to defend this statement) but yet you stated "But i do see some microsoft employees egos are easily shattered by stating a simple fact" hence the reason why I pointed you to https://github.com/microsoft/winget-cli/discussions/223 instead. 

I have told you already that the team behind Windows Package Manager are looking into these and have several improvements in the works; but you decided to take your own path here and insult people with your statements despite these issues and problems were initially known or brought up when the Windows Package Manager was announced in Q2 2020. 

> Please go back to school.
> Your replies were disrespectful, so you get disrespect back, that is how it works.
Again - please read the [Code of Conduct](https://opensource.microsoft.com/codeofconduct/) before commenting such accusing statements that are bothersome and borderline offensive to people who are reading this issue. 

And no, that is not "how this works". You don't simply revenge with someone who you don't know, and if you do, you will have to take a break and reflect on yourself - it seems like to us (and to others) that you're starting off an argument here and going around with an attitude that's perceived as unwelcome, and if that's the direction you're going around, how can **we** take you seriously, or how can *?we** allow the team behind Windows Package Manager to make improvements to their software by taking feedback from others, but can't because the feedback isn't constructive and insults engineers and contributors instead? 

How so and where? Please enlighten me about it. I would have apologized to you for that - if only you would kindly point me that "disrespectful" statement out but here you didn't? 

If it's the `It doesn't have to be mentioned` point - that statement is talking about package managers in general; there are many package managers out there; and not **every single** package manager out there needs to be called out on that. 

Most package managers out there have more or less the same functionalities as Scoop or Chocolately which, of course, the Windows Package Manager is lacking (such as `.zip` support, moving downloaded files to somewhere else, and more), and as I've said above, the team behind it is looking into improvements on how to make it better for everyone; and to make it in-line or compete with other package managers out there in the wild.
