### ISSUE TITLE
[Package Issue]: WinDirStat.WinDirStat.Beta

### ISSUE THREAD

**Issue by jamesaepp** [microsoft/winget-pkgs#182583]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

WinDirStat.WinDirStat.Beta is perpetually available for update

### Steps to reproduce

`winget update WinDirStat.WinDirStat.Beta`

### Actual behavior

The installation occurs, but the package is never removed from the winget update list.

### Expected behavior

After update, the package shouldn't show as available/reattempt update/reinstallation.

### Environment

Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4317
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled

**Comment by Trenly** [comment]
@seangibbz - I see you've been maintaining this package and using the `PackageVersion` of `2.0.0-<date>`. This leads to the package being perpetually available for upgrade since the `PackageVersion` is higher than the `DisplayVersion` that is written to the registry.  There are three ways to fix this
1) Change the `PackageVersion` to be `2.0.0` and just always update the URLs and Hashes each time a new version is released;
2) Add the `AppsAndFeaturesEntries.DisplayVersion` to the manifest. However, since all versions have the same display version, only one manifest would be able to be kept in the repo anyways (old beta version would have to be removed with each new version)
3) Have the builds of WinDirStat Beta provide the unique version

**Comment by assarbad** [comment]
The first option seems like the most logical. We can easily adjust the automation to do that and strip the remainder of the number assigned in the tag.

@Trenly any suggestions how to make it visible to the users, though? Or are we stuck with the version number that is going to be assigned to the next upcoming release? I for one would be slightly confused seeing an upgrade available when I can also see the old version and the new are apparently the same. Would it work to use the date as the version number, perhaps? Or something like major version of upcoming release, e.g. `2`, but then followed by `2024`, and `MMDD`? So something along the lines of `2.2024.1018` for an imaginary beta release today?

**Comment by Trenly** [comment]
@assarbad - great questions!

If the version is always the same, there is no way to know that the version has changed, and then we have the opposite problem where an upgrade is never available instead of being always available.

The best practice is to have each build / release of the product have a unique and increasing version number. Most publishers use something like `<major>.<minor>.<patch>.<build number>` where the bulld number is just the number of times the CI/CD pipeline has been run.  However, this doesn’t have to be the way it is done. Your suggestion of `<major>.<year>.<mmdd>` would work perfectly, since they year month and day would always be in increasing order. 

It is worth noting that WinGet can handle if the versions are not strictly increasing, such as if you did `2.0.0-<commit hash>`, it just requires a more complex manifest. However, this still requires that each release still write a unique value to the registry as the DisplayVersion.

**Comment by jamesaepp** [comment]
I believe #184041 has resolved this issue.

**Comment by assarbad** [comment]
@jamesaepp it has, but only because the first three version segments (2.0.2) differed from the previous version (2.0.0). The underlying issue is still worth figuring out.
