### ISSUE TITLE
uTorrent is missing from the manifest repository

### ISSUE THREAD

**Issue by mryujitanaka** [microsoft/winget-pkgs#1915]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by Weilbyte** [comment]
Cannot be included as their installer executable needs to be unzipped and according to the manifest spec, `winget-cli` currently does not support the zip `InstallerType` (depends on https://github.com/microsoft/winget-cli/issues/140).

**Comment by Weilbyte** [comment]
@denelon can you label as `Blocking-Issue`? Thanks!

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/140

**Comment by Trenly** [comment]
There isn't enough information here to go off of; Since this issue is so old, can you please submit a new [Package Request](https://github.com/microsoft/winget-pkgs/issues/new?assignees=&labels=Help-Wanted%2CPackage-Request&template=package_request.yml&title=%5BPackage+Request%5D%3A+) so we can better track exactly which package you're looking for?
