### ISSUE TITLE
IntelliJ IDEA Community, Ultimate and Educational Editions are missing from the manifest repository

### ISSUE THREAD

**Issue by vyujitanaka** [microsoft/winget-pkgs#1917]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by denelon** [comment]
@vyujitanaka IntelliJ depends on Java. Unless there is a bundled version available, these may not be viable to add until support for dependencies in the Windows Package Manager is implemented.

**Comment by GauthierPLM** [comment]
https://youtrack.jetbrains.com/issue/IDEA-242025

**Comment by mimi89999** [comment]
The reason is different. Unless something has changed, IntelliJ installer requires a silent config file that winget can't provide. This has already been discussed in https://github.com/microsoft/winget-pkgs/pull/179 and in other package managers https://github.com/just-install/registry/issues/115. I opened an issue upstream, but they don't seem to understand it: https://youtrack.jetbrains.com/issue/IDEA-226645

**Comment by jedieaston** [comment]
Jetbrains toolbox is available in the repo, maybe that will help as a workaround for now.

**Comment by mimi89999** [comment]
It won't. We have domain users. Installing JetBrains products on domain accounts will make them barely usable, will slow logon and will be a big waste of space on the domain server.

**Comment by mimi89999** [comment]
I added IntelliJ CE in https://github.com/microsoft/winget-pkgs/pull/5212.

**Comment by denelon** [comment]
It looks like they are all present now:

```
winget search intellij
Name                            Id                               Version  Match         Source
----------------------------------------------------------------------------------------------
RubyMine                        JetBrains.RubyMine               2020.3.3 Tag: intellij winget
CLion                           JetBrains.CLion                  2020.3.3 Tag: intellij winget
Android Studio                  Google.AndroidStudio             4.1.2.0  Tag: IntelliJ winget
IntelliJ IDEA Ultimate Edition  JetBrains.IntelliJIDEA.Ultimate  2020.3.3               winget
IntelliJ IDEA Education Edition JetBrains.IntelliJIDEA.Edu       2020.3.4               winget
IntelliJ IDEA Community Edition JetBrains.IntelliJIDEA.Community 2020.3.3               winget
```

**Comment by bdavis-tc** [comment]
**Windows 10 Install path changed unexpectedly.  Program Files vs Program Files (x86)**

On my last machine I installed IntelliJ IDEA 2019.2.2 (Ultimate Edition) using the exe downloaded from the site https://www.jetbrains.com/idea/download/#section=windows

On my current machine installed IntelliJ IDEA 2021.3.2 (Ultimate Edition) using winget

The exe installed it in Program Files
However winget installed it in Program Files (x86)
It appears to be a 64 bit application, so I think it is unexpected to find it in Program Files (x86)

Is this a bug, or intentional?

**Comment by ItzLevvie** [comment]
> Is this a bug, or intentional?

It's a bug with how JetBrains' installers work.

All WinGet does is run `ideaIU-2021.3.2.exe` with the `/S` installer switch.

**Comment by bdavis-tc** [comment]
confirmed, and to add clarification on how much of the path to provide to --location, this command gives the expected results for the current version

winget install -e --id JetBrains.IntelliJIDEA.Ultimate --location "C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.2"
