### ISSUE TITLE
Oracle's VM VirtualBox and VirtualBox Extension Pack are missing from the manifest repository

### ISSUE THREAD

**Issue by vyujitanaka** [microsoft/winget-pkgs#1921]
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by izep** [comment]
PR for virtualbox.  #2059 
I don't think the extension pack is possible at the moment.

**Comment by denelon** [comment]
'winget install Oracle.VirtualBox'

**Comment by denelon** [comment]
Is the extension pack an installer or .zip or standalone .exe? I'm not sure what the limitation is here.

**Comment by wjk** [comment]
I don’t think ever listing the extension pack here is a good idea, due to the vendor’s deliberately predatory license.

Once installed, _any_ VMs you have installed will be limited to noncommercial use only (not just the ones using the pack’s features), for as long as it is installed. One cent of revenue and Oracle's taxmen — I mean license compliance lawyers — will start to hound your company. Just uninstalling the pack will not stop them, as they would file claims based on any (even hypothetical) past usage while the pack was installed. Simply buying a license isn’t a practical avenue for end users; last I checked it costs $61 per seat per year — with a minimum purchase of 100 seats. Just one license will set you back $6,100 per year (ouch). Furthermore, Oracle regularly scans the HTTP logs for its extension pack file and proactively sends their compliance agents to the owners of IP addresses seen downloading the Pack too many times.

Disclaimer: While I first learned of the above allegations through the IT grapevine, there is one confirmed, concrete issue on this topic on GitHub that I can find that concurs with the above statements: https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1145.

_Please_ do not subject our users to this kind of trouble. Thank you.
