### ISSUE TITLE
[Package Issue]: Google.PlatformTools: adb cannot find AdbWinApi.dll

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-pkgs#195087]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

adb cannot find AdbWinApi.dll

### Steps to reproduce

1) winget install -h Google.PlatformTools
2) reload shell
3) try to run `adb reverse`

### Actual behavior

adb cannot find AdbWinApi.dll

### Expected behavior

Adb should work correctly

### Environment

```raw
Диспетчер пакетов Windows (предварительная версия) версии 1.10.40-preview
(с) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Windows: Windows.Desktop v10.0.26100.2454
Архитектура системы: X64
Пакет: Microsoft.DesktopAppInstaller v1.25.40.0

Каталоги WinGet
--------------------------------------------------------------------------------------------------------------------------------------
Журналы                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
Параметры пользователя                    %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Каталог переносимых ссылок (пользователь) %LOCALAPPDATA%\Microsoft\WinGet\Links
Каталог переносимых ссылок (компьютер)    C:\Program Files\WinGet\Links
Корень переносимого пакета (пользователь) %LOCALAPPDATA%\Microsoft\WinGet\Packages
Корень переносимого пакета                C:\Program Files\WinGet\Packages
Корень переносимого пакета (x86)          C:\Program Files (x86)\WinGet\Packages
Скачивания установщика                    %USERPROFILE%\Downloads

Ссылки
--------------------------------------------------------------------------------------
Заявление о конфиденциальности https://aka.ms/winget-privacy
Лицензионное соглашение        https://aka.ms/winget-license
Уведомления третьих сторон     https://aka.ms/winget-3rdPartyNotice
Домашняя страница              https://aka.ms/winget
Условия Windows Store          https://www.microsoft.com/en-us/storedocs/terms-of-sale

Параметр администратора                   Состояние
---------------------------------------------------
LocalManifestFiles                        Включено
BypassCertificatePinningForMicrosoftStore Отключено
InstallerHashOverride                     Включено
LocalArchiveMalwareScanOverride           Отключено
ProxyCommandLineOptions                   Включено
DefaultProxy                              Отключено
```

### Screenshots and Logs

![Image](https://github.com/user-attachments/assets/1cbdc27f-968e-40af-8b74-3f83a42bc195)

**Comment by drshtmstry** [comment]
- #2711

**Comment by iburakov** [comment]
Same here, can't find AdbWinApi.dll on any adb invokation after a usual `winget install Google.PlatformTools`.

A **workaround** is to manually add the platform-tools install dir to your PATH. For me it was:

```
%LOCALAPPDATA%\Microsoft\WinGet\Packages\Google.PlatformTools_Microsoft.Winget.Source_8wekyb3d8bbwe\platform-tools
```



<details>
<summary>Error text</summary>
The code execution cannot proceed because AdbWinApi.dll was not found. Reinstalling the program may fix this problem.
</details>

<details>
<summary><code>winget show</code> output</summary>
<pre>
C:\Windows\System32>winget show Google.PlatformTools
Found Android SDK Platform-Tools (ADB) [Google.PlatformTools]
Version: 35.0.1
Publisher: Google LLC
Publisher Url: https://developer.android.com/
Publisher Support Url: https://developer.android.com/tools#tools-platform
Description:
  Android SDK Platform-Tools is a component for the Android SDK.
  It includes tools that interface with the Android platform, primarily adb and fastboot.
Homepage: https://developer.android.com/tools/releases/platform-tools
License: Apache License
License Url: https://android.googlesource.com/platform/packages/modules/adb/+/refs/tags/platform-tools-35.0.1/NOTICE
Privacy Url: https://policies.google.com/privacy
Copyright: Copyright (c) 2006-2009, The Android Open Source Project; Copyright 2006, Brian Swetland <swetland@frotz.net>
Copyright Url: https://android.googlesource.com/platform/packages/modules/adb/+/refs/tags/platform-tools-35.0.1/NOTICE
Release Notes:
  adb
  - Switch to libusb 1.0.27
Release Notes Url: https://developer.android.com/tools/releases/platform-tools#3501_march_2024
Documentation:
  Android Debug Bridge (adb): https://developer.android.com/tools/adb
Tags:
  adb
  android
  debug
  development
  fastboot
  flash
  platform-tools
Installer:
  Installer Type: portable (zip)
  Installer Url: https://dl.google.com/android/repository/platform-tools_r35.0.1-win.zip
  Installer SHA256: fecc3f9dd1b4072717c44476314b5c83cf66c46f81ff9a4c91e659f9080c5140
  Release Date: 2024-03-20
  Offline Distribution Supported: true
</pre>
</details>

<details>
<summary><code>winget --info</code> output</summary>
<pre>
C:\Windows\System32>winget --info
Windows Package Manager v1.9.25200
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4460
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.25200.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
</pre>
</details>

**Comment by aisgbnok** [comment]
- Fixed by #190804

**Comment by aisgbnok** [comment]
This is fixed in all currently available versions. Try uninstalling and then reinstalling.

**Comment by iburakov** [comment]
The fix worked, thanks! 

Removed the manual PATH entry, reproduced the problem to double-check, then did
```
winget uninstall Google.PlatformTools
winget install Google.PlatformTools
```

Got this in the output:
```
Path environment variable modified; restart your shell to use the new value.
```

So I restarted the shell and the error is gone. All good!

**Comment by soredake** [comment]
Fixed now.
