### ISSUE TITLE
Skype-for-Business Request

### ISSUE THREAD

**Issue by dtantono** [microsoft/winget-pkgs#19814]
PackageIdentifier: Skype for Business
PackageVersion: 16.0.5
PackageLocale: en-US
Publisher: Microsoft
PackageName: Skype for Business
License: proprietary
ShortDescription: Meeting app by Microsoft
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://download.microsoft.com/download/8/7/E/87E24B50-9C85-4B1D-A581-94AA037803F8/LyncEntry_bypass_ship_x64_en-us_exe/lyncentry.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by Trenly** [comment]
Thank you for taking the time to report this issue. In the time since this issue has been opened, Skype for Business has been retired. The online infrastructure for Skype For Business has already started to be decommissioned, which will eventually render the application unusable.  You can learn more about this in the [Retirement Announcement](https://learn.microsoft.com/en-us/microsoftteams/skype-for-business-online-retirement)

###### Close with reason: Stale;
