### ISSUE TITLE
[Update Request]: Smilegate.stove

### ISSUE THREAD

**Issue by Just-A-Guy-Simp** [microsoft/winget-pkgs#199998]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Smilegate.Stove

### Package Version

2.0.0.1043

### Please describe the changes you would like to see

This current version was deprecated and an entirely new "version"/ software was released to replace it.

Download page: [https://www.onstove.com/en/download](https://www.onstove.com/en/download)

**Comment by Dragon1573** [comment]
The installer introduce itself as version `3.1.21.0`.

![Image](https://github.com/user-attachments/assets/554bf013-5085-456f-88fc-4723849a4a48)

Also [_Komac_](https://github.com/russellbanks/Komac) inspect it as `InstallerType: exe` instead of previous `nullsoft`. Did they change the technology? Do they still support silent / unattended installation?

**Comment by Dragon1573** [comment]
> Starting from v3.0, stove does not support silent install.
>
> Below is the stove installation link provided by ISV:
>
> - web: https://sgs-live-dl.game.playstove.com/game/lcs/STOVESetup.exe
> - full: https://dl.onstove.com/tools/STOVESetup/STOVESetup.exe

`winget.exe` does not support https://github.com/microsoft/winget-pkgs/labels/Interactive-Only-Installer at the moment. These `*.exe` files can't be submitted to the repository.

> - zip: https://dl.onstove.com/game/lcs/STOVE.zip

I'll try if `*.zip` can resolve the request.
