### ISSUE TITLE
vim package does not respect --location

### ISSUE THREAD

**Issue by jazzdelightsme** [microsoft/winget-pkgs#20228]
# Steps to reproduce

`winget install --id vim.vim --silent --location C:\vim`

# Expected behavior

Vim should be installed to "C:\vim", per the `--location` switch.

OR it should give me an error saying "sorry; --location is not supported for this package". (But in that case, I would then request `--location` support be added for this package. :))

# Actual behavior

No error, and vim gets installed to some place under "C:\Program files".

# Environment

```none
PS C:\Windows\system32> winget --info
Windows Package Manager v1.0.11591
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22406.1001
Package: Microsoft.DesktopAppInstaller v1.11.11591.0
```

**Comment by OfficialEsco** [comment]
oooooooook, so i did some diging while typing this comment, Nullsoft/Inno etc already have the InstallLocation switch configured so #20229 is useless.

First of all you can find the Winget log at `%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir` if you do `winget install vim.vim -l C:\Vim` you'll see `2021-07-08 20:18:57.608 [CLI ] Starting: 'C:\Users\Esco\AppData\Local\Temp\WinGet\vim.vim.8.2.3119.exe' with arguments '/S /D=C:\Vim'`.

I also tried this outside of WinGet, and it appears that the issue is with Vim ignoring the /D switch.

**Comment by denelon** [comment]
@jazzdelightsme I created the issue at the vim repository. Feel free to 👍 and or add additional comments/context.

**Comment by jazzdelightsme** [comment]
Thanks @denelon. In the meantime, can a manifest be marked "does not support --location"?

**Comment by denelon** [comment]
@jazzdelightsme that's an interesting idea. It would impact our validation, and would be a schema change. I think we should look at other "unsupported" use cases to try and get the bulk of them in one round of changes.  I'll create an issue.

**Comment by denelon** [comment]
@jazzdelightsme do you know if VIM has fixed this issue with the installer?

**Comment by jazzdelightsme** [comment]
Verified that the vim installer is now fixed.
