### ISSUE TITLE
[Update Request]: hfiref0x.WinObjEx64 2.0.5

### ISSUE THREAD

**Issue by skissane** [microsoft/winget-pkgs#203026]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

hfiref0x.WinObjEx64

### Package Version

2.0.5

### Please describe the changes you would like to see

New release: https://github.com/hfiref0x/WinObjEx64/releases/tag/v2.0.5

**Comment by DuckDuckStudio** [comment]
Hi @skissane ,
Where should I get the installer/files for this package?
![Image](https://github.com/user-attachments/assets/7936f4cb-9eb2-48a2-8f11-cc51a94c1b0f)

**Comment by Dragon1573** [comment]
Sorry to ping @hfiref0x here 🙏🏼, here's a quick brief:

We're community volunteers and want to submit manifests of your latest release. We will NOT save your builds on our devices. There's only metadata (file URL) points to that you officially hosted (the [GitHub Releases](https://github.com/hfiref0x/WinObjEx64/releases/tag/v2.0.5)).

We can't find any pre-built assets in the release (see [above comment](https://github.com/microsoft/winget-pkgs/issues/203026#issuecomment-2564642880)). Since you're the publisher of that release, did you forget to upload them? Or does it host on somewhere else?

Appreciate if you can guide us for getting the download URL. ❤

**Comment by hfiref0x** [comment]
Hello,

@Dragon1573 
>Since you're the publisher of that release, did you forget to upload them?

Indeed I forget to do that. Archive with compiled files now attached to this release, thanks.

**Comment by DuckDuckStudio** [comment]
Will be resolves by #203664 .
