### ISSUE TITLE
Removal of old versions of software which have daily nightly builds

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-pkgs#21256]
## Description of the new feature/enhancement
I think old versions of the software which have daily nightly builds should be removed and only the last 50-60 versions should be only kept. Keeping every version of the daily build is not a very good choice. For example, VLC Player and OpenJS/NodeJS.

## Proposed technical implementation details (optional)
Deleting manifests of very old versions of nightly builds of the software.

**Comment by ItzLevvie** [comment]
I'll comment here as I'm the one that made those PRs to add these versions to the repository.

I'll be **removing Node.js Nightly versions and VLC media player nightly versions that don't have** `ProductCode` (which I forgot to add when making them because `winget list` was experimental at that time) **in their manifest** as those won't register in `winget list`; unless you wanted to manually edit them and add them; but keeping the ones that do have `ProductCode` so that people are able to upgrade.

These nightly builds don't have a built-in updater unless the person decided to use Windows Package Manager or downloaded the version manually from the publisher's website to update the application. These are all `.MSI` installers too, so having `ProductCode` in the manifest is needed to map the application to `winget list` which would allow people on older versions to upgrade.

Unfortunately, "keeping the last 50 versions" is still quite little compared to your previous "keeping the last 5-10 versions". This wouldn't allow anyone who are on a 3+ months old version to update at all and you would break their `winget upgrade` which is why from my previous comment I said that it's better to keep it as is for compatibility.

One question you need to keep in mind is "What happens if you wanted to take a break or a long vacation and then come back to your computer realizing that you can't update because the version was removed from the repository by someone?" Because of this, you shouldn't underestimate how many people stay on old versions of software. There are quite a lot of people that do this, especially for preview builds and I'm definitely one of those people that's guilty of doing this.

**Comment by vedantmgoyal2009** [comment]
Hey, wait
I will be removing VLC Nightly

**Comment by vedantmgoyal2009** [comment]
Please

**Comment by ItzLevvie** [comment]
cc @vedantmgoyal2009: It's fine, I'll take care of it. These changes were done yesterday when I was digging through `winget list` and I had these branches created already, just not pushed.
