### ISSUE TITLE
App icon in manifest

### ISSUE THREAD

**Issue by khaffner** [microsoft/winget-pkgs#22577]
# Description of the new feature/enhancement
The icon of the app in question should be in the manifest. For example as base64 encoded png. 
I believe this will greatly simplify and practicly enable visually beautiful winget-integrations in other systems such as Software Center, Company Portal and the new Windows 11 Store. Or any other third party "app store" for Windows.

Another solution could be to have the icons externally and have url to icon in the manifest. But given the relatively small file size of an icon, I would lean towards having it directly in the manifest for simplicity's sake.

# Proposed technical implementation details (optional)
The packaging tools could take file path or url to png as parameters, convert to base64 and insert the string in the yaml.
To not bloat the repo too much, I suggest a resolution cap of 512x512. This cap could also be tested with winget validate.

**Comment by jedieaston** [comment]
Company Portal/Software Center/etc just grab an .ico file out of the installer, right? Any reason why they can't just keep doing that when bringing in an installer from a URL?

(I'm not trying to be down on your idea because icons are nice, it's just I'm afraid of bumping up the size of the manifests and having a big binary blob in there that we have to worry about moderating, because it's just a matter of time before someone puts something not kid friendly in the icon field).

**Comment by khaffner** [comment]
Software Center can use the exe installer as source for the icon during packaging in ConfigMgr, yes. But then the extracted png/ico gets stored in the database as base64 as a property of the app. Company Portal needs you to supply the png yourself and upload it to intune.

The intent was in my mind to make the icon available before actually downloading the installer. Just like in any app store :+1: 

I see your concern about the moderation, I did not think about that.

**Comment by OfficialEsco** [comment]
Related: https://github.com/microsoft/winget-cli/issues/1253 (and the place to post this feature idea)

**Comment by KevinLaMS** [comment]
Thanks @khaffner.  I agree with OfficialEsco.  Would you mind thumbs upping the related PR and adding your suggestions there?
