### ISSUE TITLE
Fork.Fork 1.65.0: Installer hash does not match

### ISSUE THREAD

**Issue by mloskot** [microsoft/winget-pkgs#25139]
# Brief description of your issue

Hash of Fork.Fork 1.65.0 updated in PR https://github.com/microsoft/winget-pkgs/pull/25014 does not match:

![image](https://user-images.githubusercontent.com/80741/129545636-897abc13-d44a-4f3d-b320-345a54fc7af7.png)

# Steps to reproduce

```
winget upgrade Fork.Fork
```

# Expected behavior

Successful installation (or upgrade) of Fork to 1.65.0

# Actual behavior

```
Installer hash does not match
```

# Environment

```none
[winget --info]
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.1165
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
Licence Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
```

**Comment by ImJoakim** [comment]
This application had another update to version `1.65.1` recently, and since it does not have a direct download to a specific version, the hash will not match until it's updated. You can bypass it by adding `--force` if you really want to. However, it is good to create an issue like you just did so we can update it faster :) It will be resolved once my PR gets merged 👍
