### ISSUE TITLE
"BraveSoftware/BraveBrowser" version control is broken.

### ISSUE THREAD

**Issue by koumaza** [microsoft/winget-pkgs#2546]
>>From [Brave Release note](https://github.com/brave/brave-browser/releases/tag/v1.10.97)
> ## Windows
> `BraveBrowserSetup.exe` and `BraveBrowserSetup32.exe` will fetch and install the latest available version from our update servers.

>https://github.com/microsoft/winget-pkgs/blob/06ef06d2bf57510358d3704e8e9954e90f2d4664/manifests/BraveSoftware/BraveBrowser/1.10.97.yaml#L24

Need change `BraveBrowserSilentSetup.exe` to `BraveBrowserStandaloneSilentSetup.exe`.

https://github.com/microsoft/winget-pkgs/tree/master/manifests/BraveSoftware/BraveBrowser

**Comment by OfficialEsco** [comment]
Gotchu bro, my 1.11.97 manifest is using the correct exe, the older manifests are often outdated/not correct.

Also checked the other ones, all of them use BraveBrowserSilentSetup which is why my 1.10.97 manifest also did that.

**Comment by denelon** [comment]
The version logic will look at the manifests for the given "Id" and take the max version. The PR was merged, but if any "older" manifests are > version 1.10 then the package manager will still show the 1.11.97 or which ever larger value is present on any manifest for that "Id".

**Comment by OfficialEsco** [comment]
What @koumaza means is that the BraveBrowserSilentSetup.exe and BraveBrowserSetup.exe updates to the latest Brave Version, which is why we need the BraveBrowser**Standalone**SilentSetup.exe

Sadly there is no switch to Disable auto update because the Brave team disabled it for "safety reasons". But if you really want a lower version you can block the auto update in Windows.

What you are talking about @denelon is how WinGet chooses what package to install, by default it will choose the highest version yes, but we have a -version option which is why its useful to keep "old" manifests (At least keep the main versions)

**Comment by koumaza** [comment]
> What @koumaza means is that the BraveBrowserSilentSetup.exe and BraveBrowserSetup.exe updates to the latest Brave Version, which is why we need the BraveBrowser**Standalone**SilentSetup.exe

Yes, that's right.

> Sadly there is no switch to Disable auto update because the Brave team disabled it for "safety reasons". But if you really want a lower version you can block the auto update in Windows.

It is really a pity.

I found a way to handle Brave's DNS to 0.0.0.0.
(Partly NSFW) [https://www.publish0x.com/random/stop-brave-browser-from-auto-updating-on-windows-xqwmgo#:~:text=Now%20go%20to%20the%20brave,Brave%20Browser%20from%20auto%20updating.](https://www.publish0x.com/random/stop-brave-browser-from-auto-updating-on-windows-xqwmgo#:~:text=Now%20go%20to%20the%20brave,Brave%20Browser%20from%20auto%20updating.)

> What you are talking about @denelon is how WinGet chooses what package to install, by default it will choose the highest version yes, but we have a -version option which is why its useful to keep "old" manifests (At least keep the main versions)

I think that version control of Winget will become delicious every day later.
Also, it's really nice that Manifest is easy to write.

One thing to vague.
I sometimes make `latest.yaml`, but since there is no priority, the version `*.*.*` is displayed as the latest version.
```
➜ winget search brave
Name                  Id                                 Version
----------------------------------------------------------------
Brave Browser         BraveSoftware.BraveBrowser         1.11.97
Brave Browser Nightly BraveSoftware.BraveBrowser-Nightly 1.13.31
```
```
➜ winget show Brave-Nightly --versions
Found Brave Browser Nightly [BraveSoftware.BraveBrowser-Nightly]
Version
-------
1.13.31
latest
```

**Comment by denelon** [comment]
It is possible to pass custom switches to an installer. Is there a way to specify something with a switch to tell the installer which version of Brave one wants?

The logic on the way the package manager handles the version is essentially a sort broken down by the "." in version numbers. We've been thinking about what "latest" might mean as a sentinel value, but that's not really decided. I probably shouldn't have approved the manifest with version "latest". That should be treated as a special case since the SHA will change over time.

**Comment by koumaza** [comment]
>It is possible to pass custom switches to an installer. Is there a way to specify something with a switch to tell the installer which version of Brave one wants?

It probably doesn't exist. In this case, can only replace it with "BraveBrowserStandaloneSilentSetup.exe".

>I probably shouldn't have approved the manifest with version "latest".

I agree. I think it's better to archive the binaries to support links that keep only the latest binaries.

**Comment by OfficialEsco** [comment]
Hmm, about the Latest Brave manifest i think it should be renamed/deleted because it actually points to a specific version, if you want a specific version you need to use for example `Winget install BraveSoftware.BraveBrowser -e -version 1.10.97`

We should probably use Latest for Origin (They update the installer but no version link) and Battle.net (Static SHA, updates to latest).

And/or we can use Latest for redirect links that point to the newest version, however this will only take priority on install, not update if it gets added

**Comment by denelon** [comment]
Is this resolved?

**Comment by OfficialEsco** [comment]
Yes

**Comment by koumaza** [comment]
OK. I close.
Thanks for everyone help!
