### ISSUE TITLE
No applicable update found. MusicBrainz.Picard

### ISSUE THREAD

**Issue by nascentt** [microsoft/winget-pkgs#26290]
# Brief description of your issue
PS C:\WINDOWS\system32> winget upgrade
Name                        Id                            Version        Available      Source
----------------------------------------------------------------------------------------------
MusicBrainz Picard          MusicBrainz.Picard            2.6.2          2.6.30000.0    winget
PS C:\WINDOWS\system32> winget upgrade MusicBrainz.Picard
No applicable update found.
PS C:\WINDOWS\system32> winget upgrade picard
No applicable update found.# Steps to reproduce

# Expected behavior

# Actual behavior

# Environment

```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Any other software?
```

**Comment by quhxl** [comment]
![Screenshot 2021-08-30 190202](https://user-images.githubusercontent.com/69106310/131376713-79bf9729-f297-4eaa-b374-3d2622e3dacd.png)

Can you tell me how to replicate this?

**Comment by quhxl** [comment]
This is probably caused by the fact that we use the msix installer. If you installed the software with the EXE installer, then this will often cause problems.

**Comment by nascentt** [comment]
That must be why.  I indeed originally had it installed by exe, and tried to update it via winget.
Pity, as this is likely the default situation for new winget users, wanting to maintain and upgrade their existing installs.

**Comment by vedantmgoyal2009** [comment]
> ![Screenshot 2021-08-30 190202](https://user-images.githubusercontent.com/69106310/131376713-79bf9729-f297-4eaa-b374-3d2622e3dacd.png)

Off-topic, can you please tell me which Terminal do you use?

**Comment by denelon** [comment]
@JanDeDobbeleer is the wizard behind [JanDeDobbeleer.OhMyPosh](https://github.com/JanDeDobbeleer/oh-my-posh).

**Comment by vedantmgoyal2009** [comment]
Yes, I have started using it and it's really good.

**Comment by OfficialEsco** [comment]
i swear we had the exe version before, but it might have been removed because there is a version miss match between the exe and msix.
This would cause one of the InstallerTypes to go into a `winget upgrade` loop.
This can be solved once `AppsAndFeaturesEntries` works like it should.
| url | installertype | version |
| ----- | ----- | ----- |
| https://musicbrainz.osuosl.org/pub/musicbrainz/picard/picard-setup-2.7.3.exe | Nullsoft | 2.7.3 |
| https://github.com/metabrainz/picard/releases/download/release-2.7.3/MusicBrainz-Picard-2.7.3.msix | msix | 2.7.30000.0 |
