### ISSUE TITLE
MasterPackager.MasterPackager should be removed

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-pkgs#26403]
## Brief description of your issue

MasterPackager does not download and install correctly when running `winget install MasterPackager.MasterPackager`

## Steps to reproduce

Run `winget install MasterPackager.MasterPackager`

## Expected behavior

MasterPackager should install without any errors.

# Actual behavior

```
PS C:\Users\WDAGUtilityAccount\Desktop\Tools> winget install MasterPackager.MasterPackager
Found Master Packager [MasterPackager.MasterPackager]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.masterpackager.com/installer/professional/masterpackager_21.2.7837.0.msi
  ██████████████████████████████  2.00 B / 2.00 B
Installer hash does not match; this cannot be overridden when running as admin
```

# Environment

```
PS C:\Users\WDAGUtilityAccount\Desktop\Tools> winget --info
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.168
Package: Microsoft.DesktopAppInstaller v1.12.11692.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
PS C:\Users\WDAGUtilityAccount\Desktop\Tools>
```

**Comment by vedantmgoyal2009** [comment]
Once moderators agree, I will convert my PRs #26354 #26355 #26356 #26357 #26358 to remove MasterPackager from the repo.

**Comment by quhxl** [comment]
microsoft/winget-cli#1261

**Comment by vedantmgoyal2009** [comment]
When the issue is fixed, we can re-add manifests. Also, it will affect the user's experience if the package doesn't download properly. A normal user won't come here to check the issue.

@denelon, in the upcoming manifest schema, will there be a field in the manifest where we can define custom winget settings. Like, if this particular website has an issue with `InstallerUrl`, we would define in the manifest only that winget should use wininet protocol for downloading the installer.

**Comment by denelon** [comment]
@vedantmgoyal2009, our preference would be to determine the root cause and fix it so that either network protocol works properly. Delivery Optimization has the ability to support parallel downloads, peer-to-peer downloads, and other enterprise capabilities like proxy support. As such we want to enable our customers to benefit from those features. We still have work on the back end to enable those, and they have a long lead time as they are integral with how Windows itself is built and released. We also have a couple of features on the client backlog for reporting invalid hashes and other installation failures. Those should help enable and empower customers to give us feedback.

**Comment by vedantmgoyal2009** [comment]
> When the issue is fixed, we can re-add manifests. Also, it will affect the user's experience if the package doesn't download properly. A normal user won't come here to check the issue.

?
