### ISSUE TITLE
GitHub Desktop doesn't appear to install correctly

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#272]
This issue is for cross-linking with the cli.

**Comment by shiftkey** [comment]
@denelon are there any logs or verbose commands that can run to see what `winget` is trying to do?

**Comment by spencerwooo** [comment]
I believe `winget` downloaded **GitHub Desktop Machine-Wide installer** and simply didn't execute it. I found the installer lying around inside `"C:\Program Files (x86)\GitHub Desktop Installer\GitHubDesktop.exe"`

**Comment by shiftkey** [comment]
@spencerwooo the machine-wide installer is based on the framework the team uses ([Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows)) and that probably explains the behaviour you're seeing:

> Squirrel's Releasify command generates an MSI file suitable for installation via Group Policy. This MSI isn't a general-purpose installer, this means that once you run the MSI, **users from now on will get the app installed, on next Login**.
> - [Docs](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/machine-wide-installs.md)

This is because GitHub Desktop doesn't need admin rights to install, and everything it needs lives under `%LOCALAPPDATA%` and `%APPDATA%`.

I had a shot at alternatives a while ago, but didn't really get to a point where it could be switched over.

The [Chocolatey approach](https://chocolatey.org/packages/github-desktop) here is to [use the normal installer](https://github.com/TakataSanshiro/Chocolatey-Packages/blob/master/automatic/github-desktop/tools/chocolateyinstall.ps1) which may be different to what `winget` is willing to support.

**Comment by denelon** [comment]
@shiftkey there are logs. I'm working on a better solution to locate where they land. I'm looking to add the path to the --info command.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/390

**Comment by denelon** [comment]
The log location is now output via `winget --info`
