### ISSUE TITLE
using latest version instead of version number

### ISSUE THREAD

**Issue by ghost1372** [microsoft/winget-pkgs#295]
hi, Some programs provide a download link for each version number
To create a manifest, we need to specify the version number
```
Id: Daum.PotPlayer
Version: 1.7.21212.0
Name: PotPlayer
...
```
But some programs have a fixed link and the latest version is always available through it
Therefore, I suggest that Make it possible for us to replace the version number With the latest word
Something like this:
```
Id: Daum.PotPlayer
Version: Latest
Name: PotPlayer
...
```

`winget-pkgs\manifests\Daum\PotPlayer\Latest.yaml`

**Comment by Tyriar** [comment]
Related discussion: https://github.com/microsoft/winget-pkgs/issues/278

**Comment by denelon** [comment]
The challenge here is the SHA256 hash of the installer. The "latest" manifest would become invalid as soon as the newer "version" showed up with a different hash. We also run static analysis on any binary before it is included in the repository. 

May users are intentional about wanting specific versions of software.

**Comment by Chaphasilor** [comment]
How about including a list of versions inside the manifest?  
There could be a 'lastest' version and then also additional, fixed versions if there existsa download URL for those.

This would sovle the problem of wrong version numbers if there's only a dynamic download URL where a specific version can't be selected.

It would also enable functionality like `winget show <app-name> --versions` to list all available versions and executing `winget install <app-name> -v 'x.x.x'`.

The static versions could be kept up-to-date, but this solution would prevent packages from becoming outdated simply because the latest version hasn't been pushed to the repo yet, which sometimes is the case with (linux) package managers.

**Comment by denelon** [comment]
@Chaphasilor we're looking at a few options, but we're likely to avoid trying to list every version of a package in a single manifest. Any time any of them changed, or became unavailable, we'd have to modify the manifest. We do list the versions for all current manifests:

'winget show vscode --versions'
'winget show --name Git -e --versions'

**Comment by denelon** [comment]
We are running a background process to check and see if the "Sha256" for an installer is still valid for the manifests. There is still work to automatically generate new manifests when files change. 

One of the primary use cases for package managers is to be able to install a specific version of a package. If we only have access to a "latest" version of a package from the source, this creates challenges. We're considering additional meta-data in the manifest to identify these kinds of packages.

**Comment by whoiskevinrich** [comment]
VLC is interesting in that the SHA is located next to the download for latest. I don't know if this is a common pattern, but would a SHA at the same directory of the download be an avenue to consider?

**Comment by denelon** [comment]
We've introduced automation to generate a valid manifest with the correct hash with the installer has changed at the URL provided by a manifest.
