### ISSUE TITLE
Installing SSMS returns error 1626

### ISSUE THREAD

**Issue by FurtadoPires** [microsoft/winget-pkgs#29759]
# Brief description of your issue

Trying to install / update Sql Server Management Studio using winget always return error code 1626 right after windows asked permission to execute the client.
# Steps to reproduce
`winget upgrade Microsoft.SQLServerManagementStudio` (both as user and as administrator)

# Expected behavior
Should update the existent version like it does ins the manual installation process

# Actual behavior

Installation always fail with code 1626

# Environment
Windows.Desktop v10.0.22000.194
Microsoft.DesktopAppInstaller v1.16.12653.0

**Comment by jedieaston** [comment]
It will. We'll make sure to keep all of the languages updated (in fact, I need to add the rest of them).

**Comment by FurtadoPires** [comment]
> 
> 
> It will. We'll make sure to keep all of the languages updated (in fact, I need to add the rest of them).
Thank you very much for all your efforts

**Comment by leo13003** [comment]
Hello,
Same problem of 1626 error when updating SSMS from 18.10 to 18.12.1.
There was also a MVC++ update pending (9.0.30729.4148 to 9.0.30729.6161), but in fact both were installed and it couldn't update, so I removed 4148 and now it is ok. So that's not the problem.

SSMS language is US and my Windows language is FR.
When I manually try to update, with SSMS-Setup-FRA it says it is not the right language. With SSMS-Setup-ENU it is ok.
I guess winget uses the Windows language and does not detect SSMS language.

**Comment by mkstephenson** [comment]
> Hello, Same problem of 1626 error when updating SSMS from 18.10 to 18.12.1. There was also a MVC++ update pending (9.0.30729.4148 to 9.0.30729.6161), but in fact both were installed and it couldn't update, so I removed 4148 and now it is ok. So that's not the problem.
> 
> SSMS language is US and my Windows language is FR. When I manually try to update, with SSMS-Setup-FRA it says it is not the right language. With SSMS-Setup-ENU it is ok. I guess winget uses the Windows language and does not detect SSMS language.

I am getting the same error, my system language is German but I have the English Management Studio installed and the winget upgrade also ends in the 1626 error, where the error in the logs tells me the languages are different.
