### ISSUE TITLE
Broken link for Notepad3 installer [rizonesoft.Notepad3]

### ISSUE THREAD

**Issue by nbros** [microsoft/winget-pkgs#3209]
# Steps to reproduce

Execute `winget install Notepad3`

# Expected behavior

Notepad3 installs

# Actual behavior

```
Found Notepad3 [rizonesoft.Notepad3]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading http://www.rizonesoft.com/download/6536/Notepad3_5.20.615.1_Setup.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
```

# Environment

```
Windows Package Manager v0.1.42241 Preview
Windows: Windows.Desktop v10.0.19041.450
Package: Microsoft.DesktopAppInstaller v1.10.42241.0
```

**Comment by mhm13dev** [comment]
I have checked the manifest file. It has a wrong url for the installer. That's why it won't work.

**Comment by koumaza** [comment]
@mhm13dev 
Yes, I know that.
But, Pipeline refers to the file name of the URL.
Currently, the validation cannot be cleared by the link passed by BLOB.
To solve this problem, I think we need to build an issue for the winget pipeline.

**Comment by mhm13dev** [comment]
@koumaza have you installed this package on your local machine with `winget install -m <manifest>`?
is it working on your machine?

**Comment by yigitemres** [comment]
I think that exe file is no longer exist. Also I cannot find any exe installer @ https://www.rizonesoft.com/downloads/notepad3/.

**Comment by mhm13dev** [comment]
@yigitemres yes that's what i want to say

**Comment by mhm13dev** [comment]
Notepad3 doesn't have an exe installer now. It provides its exe installer inside a zip file. I don't know how would we handle it with winget.

**Comment by koumaza** [comment]
@mhm13dev @yigitemres 
I confirmed that there is no EXE installer currently.
The old manifest does not work because rizonesoft only holds the latest artifacts.

>@koumaza have you installed this package on your local machine with winget install -m <manifest>?
is it working on your machine?

When EXE was present, local verification and installation was successful.

Currently only Zip is released.
the possibilities are to replace it with a stable version, do a CD with a different Repo, or wait for Winget to respond.
If it is Winget, it can not be operated unless Pipeline and Zip are compatible.
You can also ask the [Notepad3 Repo](https://github.com/rizonesoft/Notepad3/issues) to release the RC EXE.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/140

**Comment by SuperPat45** [comment]
Notepad 3 installer is now available unzipped in there github repository:
x64:
https://github.com/rizonesoft/Notepad3/releases/download/RELEASE_5.21.1129.1/Notepad3_5.21.1129.1_Setup.exe
x86
https://github.com/rizonesoft/Notepad3/releases/download/RELEASE_5.21.1129.1/Notepad3_5.21.1129.1_x86_Setup.exe
