### ISSUE TITLE
[New Feature]: Have Winget Bot check for existing PR's

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#32738]
### Description of the new feature/enhancement

Wingetbot opened issue #31984 but did not create an update for it; I then created PR #32355 and linked it to the issue. After this, Wingetbot opened #32435. This behavior causes a few things which I believe can be resolved:
1. If there is already an existing PR open, I believe that Wingetbot should not create a new one, since it is likely that a manually created PR will have been checked more thoroughly for accuracy. I do understand that this logic would have to be somewhat complex to account for when packages are intended to be modified rather than updated
2. If the previous version is unavailable and Wingetbot determines that it can be upgraded because it is a vanity URL, Winget bot should automatically remove the old version in the same PR as it creates the new version
3. It seems like Wingetbot does not immediately attempt to perform an automatic update if it determines that a package is unavailable, or that there is some issue with the retry logic which causes it to wait to create the update PR until several hours after it determines the package is unavailable, even though it is just a new version at the vanity URL. It seems other packages which use vanity URL's don't have the "version unavailable" issues filed, so perhaps there is something about this package which is causing this different behavior?

**Comment by denelon** [comment]
Initially, we're just going to check a new PR for a given package/version and if we see an open PR for the same package/version, we'll add a comment (and maybe a label for possible-duplicate) to help the PR author decide what to do. Sometimes they might close the newer PR since one is in flight, and in other cases, they might decide to keep their PR open because the other one is either incomplete or not quite right.

For the specific case of wingetbot creating PRs, it's much more complicated to have it essentially ignore creating a new PR for the hash-mismatch on a vanity URL case.

Moderators should be able to request we close the PR for wingetbot or add comments in the PR to close wingetbot's PR when the community submitted one is preferred.
