### ISSUE TITLE
Duplicate entries for remote.it

### ISSUE THREAD

**Issue by stvhwrd** [microsoft/winget-pkgs#3376]
Proposing the consolidation of [remot3-it/remote-it/v2.6.2.yaml](https://github.com/microsoft/winget-pkgs/blob/master/manifests/remot3-it/remote-it/v2.6.2.yaml) and [remot3it/remoteit/2.5.32.0.yaml](https://github.com/microsoft/winget-pkgs/blob/master/manifests/remot3it/remoteit/2.5.32.0.yaml)

These have two different paths in the repo but seem to be different versions of the same product.
I'm happy to create the PR to merge both of these under `remote-it` - the stylized `remot3-it` and `remot3it` are taken from branding.

**Comment by OfficialEsco** [comment]
When you see error like this you should just make a PR for it, probably gone unnoticed since none have updated remote-it since June when everybody submitted their first Manifest...

Those 2 manifests seems to be quite different, so it would be smart to give them the same and correct data when you're moving them

**Comment by denelon** [comment]
Feel free to create a PR with the "most accurate" representation of the package. As there aren't very many different versions, I think it's likely OK as well based on what @OfficialEsco said.

**Comment by piraces** [comment]
I would like to help on this, if you see it ok 😄

**Comment by piraces** [comment]
Please see the linked PR https://github.com/microsoft/winget-pkgs/pull/3892.
I have normalized the directories as @OfficialEsco said, and added the latest version of the app.
I am aware of the limit of one manifest per PR, but since there are general changes around the app, I decided to add the latest version too.

Please, tell me if something is wrong to correct it.

**Comment by OfficialEsco** [comment]
Annoyingly they don't accept valid PRs with the original "deleted" (because name change + manifest change) and one with the updated manifest... My guess is you have to do 5 PRs.. 2 deletions and 3 submits..

**Comment by piraces** [comment]
Wow... I think they should take a look at the PR first and override the checks manually... it is not a very complex change... The 2 deletions and 3 submits would be asynchronous and confusing (in my opinion).

What would be the best approach for this case @denelon ?

**Comment by denelon** [comment]
We've got some work coming to enable a pair of changes (one delete one add) that will hopefully help. We've also been discussing how to deal with duplicate entries (via some kind of redirect for package renames).

**Comment by Trenly** [comment]
@denelon Can this be closed now?

Reference #17512 #17496 #17495 #14990 #14681
