### ISSUE TITLE
[Bug]:  YamlCreate prompts locale multiple times

### ISSUE THREAD

**Issue by kdpuvvadi** [microsoft/winget-pkgs#33988]
### Brief description of your issue

YamlCreate.ps1 prompting for Locale on multiple times

### Steps to reproduce

```bash
$ ./YamlCreate.ps1
```

Select `New Manifest or Package Version`.

### Expected behavior

Only ask for locale once and prompt to ask if the user wants add multiple locale. 

### Actual behavior

Not asking for additional prompt, getting duplicate locale.  

### Environment

```shell
Windows Package Manager v1.1.12701
Windows: Windows.Desktop v10.0.22000.282
Package: Microsoft.DesktopAppInstaller v1.16.12701.0
```

**Comment by Trenly** [comment]
There is a difference between PackageLocale and InstallerLocale, which is why it is prompted for twice.

The InstallerLocale is the locale or language that the installer is presented in, and is an optional key which applies to each installer individually.

The PackageLocale is the locale or language that the metadata is in, and is a required key. This is also the locale for the defaultLocale file within the manifest.
