### ISSUE TITLE
[Package Request]: Window Centering Helper

### ISSUE THREAD

**Issue by EricMGVS** [microsoft/winget-pkgs#34591]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Kamil Szymborski
Publisher Url: https://kamilszymborski.github.io/
Package Name: Window Centering Helper
Description: Can center windows manually or automatically
Package Version: 1.2.11.0
Installer URL: https://kamilszymborski.github.io/WindowCenteringHelper-SE.exe

**Comment by Amoenus** [comment]
`winget` does not cater very well to software without version specific installer links. I'd suggest contacting the author and asking to support versioned installers

**Comment by Trenly** [comment]
I think its just a matter of old links not being natively available through their website. Because they are hosting the files on their Github though, it looks like we may be able to pull versioned installer links from the old commits.

For example, here is a link to v1.2.11 which should be a permalink - https://github.com/KamilSzymborski/kamilszymborski.github.io/raw/8971bc333b91d50e0ab7b20d022c6dc3b5aea5d8/WindowCenteringHelper-PE.exe

**Comment by monkeymoong** [comment]
is it possible to change icon in systray ?
