### ISSUE TITLE
 Android

### ISSUE THREAD

**Issue by yezz123** [microsoft/winget-pkgs#3680]
**_Android studio_** is missing from the manifest repository

**Comment by jedieaston** [comment]
Currently, this is blocked by microsoft/winget-cli#137 since the Android Studio installer returns code 1223 even though it installs successfully. Once that's cleared up, winget will be able to install it (#843 is a currently open PR for Android Studio, it'll have to be updated to the latest version once the other issue is closed).

**Comment by jedieaston** [comment]
Also, as a workaround (something I didn't think about until today), JetBrains Toolbox can install and update Android Studio and it *is* available via winget (winget install Jetbrains.Toolbox). That could get you by until the other issue is resolved.

**Comment by denelon** [comment]
Thanks @jedieaston

**Comment by yezz123** [comment]
Thanks @jedieaston & @denelon

**Comment by jcormier** [comment]
I ran winget install Google.AndroidStudio and it installed without error but I cannot find Android Studio in the start menu.  And am unsure where it installed it in Program Files.  Am I missing something?

**Comment by jcormier** [comment]
I guess the install wasn't successful.  I checked Add/Remove applications and it wasn't listed.  Reran winget and this time it showed up after install... Not sure what went wrong the first time but all is well.
