### ISSUE TITLE
[Bug]: ClipX is reinstalling at each upgrade

### ISSUE THREAD

**Issue by narnaud** [microsoft/winget-pkgs#40779]
### Brief description of your issue

The bluemars.ClipX.Beta package is reinstalling all the time. It probably comes from the version number, which is "1.0.3.9 Beta 7".

### Steps to reproduce

winget install bluemars.ClipX.Beta
winget upgrade --all

### Expected behavior

Does not reinstall clipx

### Actual behavior

clipx is reinstalled everytime

### Environment

```shell
Windows Package Manager v1.1.13405
Windows: Windows.Desktop v10.0.19044.1466
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by OfficialEsco** [comment]
Resolved the Manifest issues..
However the upgrade loop is caused by the Publisher not creating a DisplayVersion, you'll need to contact the dev about the issue and do a Hotfix in the meantime

Open regedit
Go to `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\ClipX`
Create a `String` called `DisplayVersion`
Set the `Value` to the version you got installed, i would recommend reinstalling the version so you get `1.0.3.8`

**Comment by jedieaston** [comment]
This should stop happening when https://github.com/microsoft/winget-cli/pull/1765 makes it into a release (no ETA yet, unfortunately).

**Comment by narnaud** [comment]
Thank you, indeed it's fixing the issue. Cheers.

**Comment by narnaud** [comment]
Forget to close the issue.
