### ISSUE TITLE
Wingetcreate Cant store token

### ISSUE THREAD

**Issue by Xanthus58** [microsoft/winget-pkgs#55135]
```
PS C:\Users\pikac> wingetcreate token -s [Redacted]
Setting GitHub token...
A GitHub account or personal access token must be linked in order to continue with this command.
Execution of the command is paused until the GitHub login has been completed.

Initiating GitHub login...

Launching web browser... If default web browser does not launch, please go to:
Please enter the following user verification code when prompted:

System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.WingetCreateCLI.GitHubOAuth.OpenWebPage(String uri)
   at Microsoft.WingetCreateCLI.Commands.BaseCommand.GitHubOAuthLoginFlow()
   at Microsoft.WingetCreateCLI.Commands.BaseCommand.GetTokenFromOAuth()
   at Microsoft.WingetCreateCLI.Commands.TokenCommand.Execute()
   at Microsoft.WingetCreateCLI.Program.Main(String[] args)
   ```

I'm unable to submit my new token since my last one expired. I've attached the error above, I have attempted to reinstall Winget, Wingetcreate, And the App installer in its entirety. Still have the same issue. If i could get some help that would be great. Thank you.

**Comment by Trenly** [comment]
Is this the same as https://github.com/microsoft/winget-create/issues/241 ?

**Comment by Xanthus58** [comment]
> Is this the same as [microsoft/winget-create#241](https://github.com/microsoft/winget-create/issues/241) ?

Yeah seems to be about right. I never saw it when posting mine

**Comment by OfficialEsco** [comment]
That is because this is the wrong repo
- https://github.com/microsoft/winget-cli is the winget client
  * This is the place to report any issues regarding the WinGet Client
  * Or any feature request for the WinGet Client
- https://github.com/microsoft/winget-pkgs is the winget-pkgs source
  * Here you can report any issues regarding our packages
  * Or issues regarding YamlCreate.ps1
  * Or request new Packages/Version for existing Package
- https://github.com/microsoft/winget-create is wingetcreate
  * Here you can report issues regarding wingetcreate
  * Or any feature request regarding wingetcreate

Duplicate of https://github.com/microsoft/winget-create/issues/241

**Comment by Xanthus58** [comment]
My apologies <3
