### ISSUE TITLE
[Package Issue]: WildfireGames.0AD | 0.0.24b is detected as update for r25860-alpha

### ISSUE THREAD

**Issue by Sky-NiniKo** [microsoft/winget-pkgs#56595]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Winget wants to upgrade to 0.0.24b while 25860-alpha is installed.
NB: r25860-alpha is the name of version 0.0.25b. I don't know why it's called that but it is.

### Steps to reproduce

Have version 0.0.25b installed and try to update.

### Actual behavior

Update to 0.0.24b.

### Expected behavior

Do not update.

### Environment

```shell
Windows Package Manager v1.2.10271
Windows: Windows.Desktop v10.0.19043.1586
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

0 A.D.: v0.0.25b
```

### Screenshots and Logs

```
PS C:\Users\User> winget upgrade
Name                                                 ID                                     Version        Available      Source
--------------------------------------------------------------------------------------------------------------------------------
0 A.D.                                               WildfireGames.0AD                      r25860-alpha   0.0.24b        winget


PS C:\Users\User> winget upgrade 0ad
Found 0 A.D. [WildfireGames.0AD] Version 0.0.24b
The license to use this application is granted to you by its owner.
Microsoft is not responsible for and does not license third-party packages.
Downloading https://releases.wildfiregames.com/0ad-0.0.24b-alpha-win32.exe
  ██████████████████████████████  0.00 B /  845 MB
Package download canceled.
```

**Comment by Trenly** [comment]
It seems that when `0.0.24b` was added, the version wasn't set to what is shown in the `A`dd/`R`emove `P`rograms (ARP) Table, which is causing this mismatch. 

I've created the above PR which should solve the issue of there being an upgrade reported;

> NB: r25860-alpha is the name of version 0.0.25b. I don't know why it's called that but it is.

It is called that because that is what the version is set to in the ARP table
```
DisplayName DisplayVersion Publisher      ProductCode
----------- -------------- ---------      -----------
0 A.D.      r25860-alpha   Wildfire Games 0 A.D.
```
Unfortunately, the `0.0.24b` and ``0.0.25b` etc. are "Marketing Versions", meaning that is what is stated the version is, but it isn't the version that is reported. Once microsoft/winget-cli#1952 is implemented, it will make it easier to differentiate between the marketing versions and reported versions, but as of right now we have to use the reported version.
