### ISSUE TITLE
Update Clink manifest

### ISSUE THREAD

**Issue by rashil2000** [microsoft/winget-pkgs#5851]
# Description of the new feature/enhancement

The current manifest for Clink points to an abandoned project. There's a fork by @chrisant996 which is regularly maintained and has made hundreds of improvements to the project. It'd be a good idea to update the manifest here with this version.

# Proposed technical implementation details (optional)

Scoop's main bucket has implemented it like this https://github.com/ScoopInstaller/Main/blob/master/bucket/clink.json

**Comment by OfficialEsco** [comment]
I was gonna say what are we going to call the Publisher? Are we separating them or do both go under MRidgers?
But then i realized the installer is Ziped, which is not supported yet.

**Comment by rashil2000** [comment]
@chrisant996 Could you help out here? Maybe with an exe installer.

**Comment by chrisant996** [comment]
Mridgers has been incommunicado for a couple years.

My fork does not have an official release yet (all releases are marked as pre-release). I've not yet built the exe installer even once. I'll get to that, but i think updating everything this early to point at my fork is jumping the gun a bit.

@rashil2000 I appreciate your interest and helpfulness. Maybe talk with me first, so that things can be corrugated coordinated and avoid confusion or complications.

**Comment by rashil2000** [comment]
Winget already has preview versions of various apps. What I wasn't aware of was that it doesn't support zips. Sorry for the confusion.
