### ISSUE TITLE
[New Feature]: use same winget version in Sandbox as on host

### ISSUE THREAD

**Issue by dpprdan** [microsoft/winget-pkgs#59429]
### Description of the new feature/enhancement

While looking into #59427 I noticed that the winget version in the Windows Sandbox (invoked via [.\Tools\SandboxTest.ps1](https://github.com/microsoft/winget-pkgs/blob/master/Tools/SandboxTest.ps1)) is not the same as on my host machine. Would it be possible / wouldn't it be preferable for the two versions to match?

This is the version info `winget --info` shows in the sandbox (i.e. current release)

```
Windows Package Manager v1.2.10271
Windows: Windows.Desktop v10.0.19041.1645
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

and on the host (current preview version)

```
Windows Package Manager (Preview) v1.3.431-preview
Windows: Windows.Desktop v10.0.19044.1645
Package: Microsoft.DesktopAppInstaller v1.18.431.0
```

**Comment by Trenly** [comment]
SandboxTest.ps1 uses the latest official release because it is meant to test if a manifest will work with the currently released cli, since the official releases are what anyone who is a “standard user” will be on. It is important to use the latest release for testing manifests because they must work with the latest stable release and not just the latest preview release. Consider the upcoming preview release, which will likely include the first cut of portable app support. That feature won’t be available to anyone using the stable client, and will have to be enabled using experimental features. Therefore, defaulting to the latest stable release is the intended behavior, to ensure accurate results when testing manifests.


If you wish to specifically test using the preview cli, however, you can use the `-Prerelease` switch when invoking SandboxTest.ps1.

**Comment by dpprdan** [comment]
That sounds reasonable. Thanks a lot @Trenly!!
