### ISSUE TITLE
[P.S.A]: DotNet Breaking Changes

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#60134]
### Description of the new feature/enhancement

The Microsoft .NET team will be making [breaking changes](https://github.com/dotnet/core/issues/7428) to the .NET manifests. Please do not modify these manifests. We will be implementing the "Verified Developer" feature for these manifests so they can manage their manifests going forward as a part of their automated publishing processes.

**Comment by jedieaston** [comment]
If we find issues with the manifests, what repo should we file them under? dotnet/core?

**Comment by denelon** [comment]
Please don't make any PRs for them. I'm coordinating with the team. I'll either get an alias to mention here, or guidance on the best way to reach out to them.

**Comment by GNQG** [comment]
Some opinions:

1. `ProductCode` is required to find local install info correctly.

2. `PackageVersion` should match exact version (i.e. 6.0.5.31213, not 6.0.5 .)

3. Current dotnetRuntime.* is subdivided by arch to install/uninstall the runtime for each arch separately because some app uses x64 runtime, and another uses x86 one. When we install a runtime with new manifests, we no longer detect which arch is used for the installed runtime via winget cli:

```
$ winget install Microsoft.DotNet.Runtime.6 -a x64

$ winget list Microsoft.DotNet.Runtime.6
Name                        ID                          Version
Microsoft .NET Runtime 6.0  Microsoft.DotNet.Runtime.6  6.0.5.31213    # <- which arch?

$ winget install Microsoft.DotNet.Runtime.6 -a x86

$ winget list Microsoft.DotNet.Runtime.6
Name                        ID                          Version
Microsoft .NET Runtime 6.0  Microsoft.DotNet.Runtime.6  6.0.5.31213
Microsoft .NET Runtime 6.0  Microsoft.DotNet.Runtime.6  6.0.5.31213   # <- same ID, same version?
```

So IMHO until winget cli gets ability to show arch in listing packages and to specify arch in uninstallation process we should use manifests like Microsoft.DotNet.Runtime.6.x64.
