### ISSUE TITLE
[Package Issue]: Microsoft.DotNet.DesktopRuntime.6 version 6.0.5 actually installs 6.0.4

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-pkgs#61981]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Microsoft.DotNet.DesktopRuntime.6 version 6.0.5 actually installs version 6.0.4

### Steps to reproduce

Run `winget install Microsoft.DotNet.DesktopRuntime.6`

### Actual behavior

version 6.0.5 should be installed.

### Expected behavior

version 6.0.4 installed

### Environment

```shell
Windows 程序包管理器(预览) v1.3.1251-preview
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22621.1
系统体系结构: X64
程序包: Microsoft.DesktopAppInstaller v1.18.1251.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

![image](https://user-images.githubusercontent.com/9316590/170270052-ff453f80-c70f-404a-91a6-baa9d24b9868.png)
![image](https://user-images.githubusercontent.com/9316590/170270108-76bb37b6-3b6e-453c-809d-43534bbd8597.png)

**Comment by mthalman** [comment]
Nothing wrong with the winget packages here. It is installing the 6.0.5 version. You should be looking at the `C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App` directory to verify that. You're looking at the `C:\Program Files\dotnet\shared\Microsoft.NETCore.App` directory.

There does seem to be something wrong with the WindowsDesktop installer though since, as you point out, it's including 6.0.4 of the runtime. I've logged https://github.com/dotnet/installer/issues/13871 for that.

But as far as the winget packages themselves, there's not an issue with them.
