### ISSUE TITLE
[Package Request][New Version Available]:  Thunderbird Beta

### ISSUE THREAD

**Issue by roworu** [microsoft/winget-pkgs#62271]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Current package for Thunderbird Beta seems to be outdated
Publisher: Mozilla
Publisher Url: https://www.thunderbird.net/en-US/
Package Name: Thunderbird Beta
Description: Thunderbird is a free email application that's easy to set up and customize!
Package Version: 101.0b4  (current in winget repo  is 99.0b2)
Installer URL: https://download.mozilla.org/?product=thunderbird-101.0b4-SSL&os=win64&lang=en-US

Current Package Identifier (for new versions): Mozilla.Thunderbird.Beta 99.0b2

**Comment by KaranKad** [comment]
Latest available through winget is `102.0b2` at the moment https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Mozilla/Thunderbird/Beta/102.0b2. 
This issue can be closed.

**Comment by roworu** [comment]
Many thanks for update!

**Comment by Gorrrg** [comment]
Please remove this package or fix its manifest because winget cannot distinguish between "Mozilla.Thunderbird.Beta" and the stable version. When I remove the stable version "Mozilla.Thunderbird.Beta" is removed, when I reinstall the stable version "Mozilla.Thunderbird.Beta" appears again. This isn't correct. I have version 115.2 installed not version 117.0b4!
