### ISSUE TITLE
Chrome manifest link does not reference a specific version

### ISSUE THREAD

**Issue by jasperweiss** [microsoft/winget-pkgs#627]
The link in Google Chrome's manifest points to whatever happens to be the latest version (83.0.4103.61 at the time of writing) rather than the version listed in the manifest (78.0.3904.87). Therefore the hash will fail to verify.

**Comment by maxmichels** [comment]
This is because in the manifest the updater is referenced. This will download the newest version and install it.

I will search if i can find the direct link to one specific version to insert it into the manifest file. Then the hash will not change after download.

**Comment by Bodup** [comment]
Honestly I don't understand why that would even be allowed in the repository. It explicitly mentions a version number and hash only to then point to whatever happens to be the latest version. Essentially training the user to just ignore the hash verification whenever it complains. 
The hash verification shouldn't even allow the installation to continue if it fails but that's [another issue](https://github.com/microsoft/winget-cli/issues/289)

**Comment by maxmichels** [comment]
Yes exactly. This could be complicated for many "newer" Softwareproducts. It is difficult to get the direct links and be sure you always will get the mentioned version. Even if you get the direct link to version X, then you download and install Chrome will start directly to download version Y.

**Comment by dmex** [comment]
@maxmichels 

You probably need to use the alternate chrome installer. The page is listed here under the collapsed "Install chrome offline" section: https://support.google.com/chrome/answer/95346

Links to standalone download page:
https://www.google.com/intl/en/chrome/browser/desktop/index.html?standalone=1

The download link includes some extra references which probably determine the appropriate version otherwise you can shorten the full installer link to:
https://dl.google.com/tag/s/installdataindex=empty/chrome/install/ChromeStandaloneSetup64.exe

**Comment by maxmichels** [comment]
Yes, but this changes also every time a new version is released. I guess only solution would be to store it at some other download location like selfhosted publicly accessible to make sure the mentioned version is downloaded. But this would require that this community package relies on someone’s hosted version of the software not provided by the software maintainer.

**Comment by dmex** [comment]
> his changes also every time a new version is released

Either way the chrome package for winget should use the url for the full installer instead of the url to download the launcher which then downloads the full installer.

> I guess only solution would be to store it at some other download location like selfhosted

If it was selfhosted you would have to validate the digital signature to ensure its legitimate and validating the signature instead of the hash fixes the issue with the hashes changing with each update.

The chrome binaries are digitally signed and winget can easily validate the thumbprint and/or common name of the embedded signature using the WinVerifyTrust function instead of the hash so this won't be an issue.

**Comment by maxmichels** [comment]
> If it was selfhosted you would have to validate the digital signature to ensure its legitimate and validating the signature instead of the hash fixes the issue with the hashes changing with each update.

but currently this is not implemented. also then the maintainers need to specify when to check the hash and when to check the certificate or both.

i think this is something which should be considered generally for winget in the future.

**Comment by dmex** [comment]
I've suggested the feature here: https://github.com/microsoft/winget-cli/issues/307

**Comment by denelon** [comment]
We now have automation for packages at vanity URLs to generate a PR with the updated hash.
