### ISSUE TITLE
Add SysInternals tools

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/winget-pkgs#650]
# Description of the new feature/enhancement

Should have the commonly used SysInternals tools as part of the index. See list of tools here: https://docs.microsoft.com/en-us/sysinternals/

**Comment by LukasNespor** [comment]
I agree, but winget does not support (yet) custom installation procedure e.g. using PowerShell. Package has to point to installer (exe, msi) that is responsible for installation istself. Sysinternals tools are unfortunately packed in zip.

**Comment by chrpai** [comment]
@markrussinovich   https://twitter.com/chrpai/status/1263561746410856449

**Comment by malxau** [comment]
See Mark's comment at https://github.com/microsoft/winget-cli/issues/140#issuecomment-628917702

**Comment by chrpai** [comment]
Wish respect, I can't agree with Mark at all.  Just create an installer already. The tool is only 20+ years old.

I see this with multiplatform tools.  They only give you a ZIP or EXE to download with no installer. If you ask about it they say   oh just use  install something /usr/local/bin.  Well this is windows not linux.  I don't want to manually go create some directory in my profile, add it to the path, download a zip and extract.  I just want to download and run an msi or in this case  winget install sysinternals.

**Comment by malxau** [comment]
Nobody is suggesting that you should manually create a directory and add it to your path with winget.

The question is whether the package should own this operation (via an installer) or whether winget should own the operation.  It may be true that creating an MSI installer is relatively straightforward, but note that it needs to be done for each package, including each cross platform package, whereas a solution in winget applies to all packages.  Have you tried Chocolatey? The experience there is you install it, specify a location, and all of your tools are populated in that location.

Both approaches have good and bad points.  The good thing about storing everything together is you can decide, once, what behavior you want - whether you want a per machine or per user install for example, and have everything follow it.  The bad thing about storing everything together is the potential for DLL conflicts, which is why Chocolatey ended up with shimgen, so each executable has a private directory with its private DLLs, but with a single location for executables that shims to the private location.

**Comment by michael-hawker** [comment]
I think the key point of a package manager like winget/chocolatey etc... as well is that it's just as easy to uninstall a package as it is to install it. Otherwise, you leave stale state on the system and degrade the experience later.

If winget has some mechanism for a manifest entry for the package to have steps 1) download 'zip' from here, 2) unzip to 'default central package location', 3) add 'something.exe' to path, that'd be great, then maybe can support both scenarios. As long as there's also a way for that to also include an uninstall step in case the program puts files elsewhere on run.

**Comment by chrpai** [comment]
I've done most of the work by creating an MSI for sysinternals suite.  You can find it at https://github.com/iswix-llc/SysinternalsSuiteInstaller/releases 

Note: This does not violate the EULA because it doesn't contain the binaries.  The user downloads the ZIP during the installation procedure.  The installer will:

1) Prompt user for location to download zip from (self hosting offline scenarios)
2) Download and extract ZIP to installation directory
3) Place installation directory at end of system path
4) Create start menu shortcut that points to installation directory.

Next step is for me to create a WinGet YAML request and see if they will merge it or not.

**Comment by chrpai** [comment]
PR submitted https://github.com/microsoft/winget-pkgs/pull/1288

**Comment by chrpai** [comment]
My PR was rejected and this raises governance concerns on this project.  The README.md instructs developers to submit manifests for their favorite applications and that is exactly what I have done.  I will escalate this issue with opencode.

**Comment by denelon** [comment]
This depends on https://github.com/microsoft/winget-cli/issues/140 and/or possibly https://github.com/microsoft/winget-cli/issues/182.

**Comment by denelon** [comment]
```
PS C:\Users\denelon> winget search sysinternals
Name               Id           Version Source
------------------------------------------------
Sysinternals Suite 9P7KNL5RWT25 Unknown msstore
PS C:\Users\denelon> winget install 9P7KNL5RWT25
```
