### ISSUE TITLE
[Package Issue]: Mozilla.Firefox

### ISSUE THREAD

**Issue by trparky** [microsoft/winget-pkgs#67793]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Winget keeps telling me that the "Mozilla Maintenance Service" requires an update yet when I execute "winget upgrade Mozilla.Firefox" it tells me "No applicable update found".

### Steps to reproduce

1. Execute "winget upgrade".
2. See how it tells you that you need an update to something called the "Mozilla Maintenance Service".
3. Execute "winget upgrade Mozilla.Firefox".
4. Winget tells you "No applicable update found".

### Actual behavior

I explained it all in the "Steps to reproduce" section.

### Expected behavior

Well, maybe no required update. At least, I think so.

### Environment

```shell
PS C:\Users\trpar> winget --info
Windows Package Manager (Preview) v1.4.2011-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.832
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.2011.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by Trenly** [comment]
This is an issue where Mozilla's auto-upgrader inside the browser does not upgrade the Mozilla Maintenance Service. A change was recently made to the Mozilla Firefox manifest which removes the Maintenance Service from the manifest, which should resolve this issue. I would suggest trying a `winget source update` to force a source refresh and see if the issue persists. If it does still persist, try running `winget install Mozilla.Firefox` (note - you may need to delete the `%TEMP%/WinGet` folder and use v1.3 of the client due to a bug with MSI installation on v1.4).

**Comment by trparky** [comment]
Thank you, I forced an upgrade with, as you said, `winget install Mozilla.Firefox`.
