### ISSUE TITLE
[Package Request]: Revopoint Revo Studio

### ISSUE THREAD

**Issue by myokeeh** [microsoft/winget-pkgs#68817]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Revopoint
Publisher Url: https://www.revopoint3d.com/
Package Name: RevoPoint Revo Studio
Description: 3D scan data editing software
Package Version: 3.0.6.9 Beta
Installer URL: https://www.revopoint3d.com/wp-content/uploads/download/Revo_Studio_for_win_v3.0.6.9.20220527.zip

Current Package Identifier (for new versions):

**Comment by myokeeh** [comment]
The zip file contains an installer.

**Comment by mdanish-kh** [comment]
> The zip file contains an installer.

Winget currently does not support installers inside of a zip archive. The issue is being tracked here https://github.com/microsoft/winget-cli/issues/140 and being experimented in the preview build https://github.com/microsoft/winget-cli/releases/tag/v1.4.2161-preview, so it's only a matter of time until we get zip support.
