### ISSUE TITLE
[Package Issue]: Miro.Miro

### ISSUE THREAD

**Issue by khaffner** [microsoft/winget-pkgs#70072]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Hash mismatch might indicate that the installer has been signed with a new cert, is not necessarily a new version of the app.

See #68869
Hashes mismatch, the bot upgrades to Miro 0.7.17. But Miro is still 0.7.16
![image](https://user-images.githubusercontent.com/13216618/184653948-2a89a552-ff6c-40f6-bdfe-462cfd1b570f.png)

I believe the hash mismatch is due to a new certificate used to sign the installer.
![image](https://user-images.githubusercontent.com/13216618/184654139-daeb54c8-51bf-4511-91c9-88a48bc716ef.png)

So the fix for hash mismatch in this case would be to just update the hashes in existing manifest for 0.7.16
Why did the bot assume this is a new version and why did tests run successful? Does the test not take version number into account?

### Steps to reproduce

winget install Miro.Miro

### Actual behavior

Reporting hash mismatch. Can be overridden and installs successfully with --force parameter

### Expected behavior

Matching hashes

### Environment

```shell
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.856
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0
```

**Comment by Trenly** [comment]
> Why did the bot assume this is a new version and why did tests run successful?

It doesn't assume a new version number. It uses the information from the VersionInfo property of the exe file. In this case, it seems Miro released a patch to 0.7.16 but forgot to change the version number of the file back. This would explain the new hash mismatch too, if they removed that version and then replaced it with a new version for 0.7.16

> Does the test not take version number into account?

The PackageVersion doesn't always exactly match what is written into control panel, so it isn't compared against in the test. If there are AppsAndFeaturesEntries specified in the manifest, they must match exactly and are compared against. Otherwise, the tests just make sure the application can install silently and isn't malware
