### ISSUE TITLE
Rust 1.62 (MSVC 64-bit)  update not reflected

### ISSUE THREAD

**Issue by xarthurx** [microsoft/winget-pkgs#72072]
### Brief description of your issue

`winget upgrade --all` or `winget install rustlang.rust.msvc` installed new version of `Rust`, but winget cannot recognize it.

```
Rust 1.62 (MSVC 64-bit)                   Rustlang.Rust.MSVC                    1.62.1.0         1.63.0           winget
```

### Steps to reproduce

`winget upgrade --all` or `winget install rustlang.rust.msvc`

### Expected behavior

New version of rust is installed and recognized.

### Actual behavior

New version of rust is installed but not recognized.

### Environment

```shell
Windows Package Manager v1.3.2091
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.856
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0
```
```

**Comment by denelon** [comment]
The default upgrade behavior isn't set to "uninstall previous". I'm not sure if that's the desired behavior for Rust.

**Comment by vedantmgoyal2009** [comment]
I'll be making the changes shortly.

**Comment by OfficialEsco** [comment]
The issue is caused by the Rust installer not removing the old version, so the real question is, does it hurt to uninstall the previous version? Aka do people work with a specific Rust version?
PRs about to change the Upgrade Behavior:
* https://github.com/microsoft/winget-pkgs/pull/72079
* https://github.com/microsoft/winget-pkgs/pull/72080
* https://github.com/microsoft/winget-pkgs/pull/72081
* https://github.com/microsoft/winget-pkgs/pull/72083
* https://github.com/microsoft/winget-pkgs/pull/72085
* https://github.com/microsoft/winget-pkgs/pull/72086
* https://github.com/microsoft/winget-pkgs/pull/72087
* https://github.com/microsoft/winget-pkgs/pull/72088
* https://github.com/microsoft/winget-pkgs/pull/72089
* https://github.com/microsoft/winget-pkgs/pull/72090
* https://github.com/microsoft/winget-pkgs/pull/72091
* https://github.com/microsoft/winget-pkgs/pull/72092
* https://github.com/microsoft/winget-pkgs/pull/72093
* https://github.com/microsoft/winget-pkgs/pull/72095
* https://github.com/microsoft/winget-pkgs/pull/72096
* https://github.com/microsoft/winget-pkgs/pull/72097
* https://github.com/microsoft/winget-pkgs/pull/72098
* https://github.com/microsoft/winget-pkgs/pull/72099
* https://github.com/microsoft/winget-pkgs/pull/72100

**Comment by Trenly** [comment]
Since the upgrade behavior has been changed, this issue should be resolved

###### Close with reason: Changes implemented;
