### ISSUE TITLE
[Package Issue]: JohnTaylor.less - lesskey not installed

### ISSUE THREAD

**Issue by rollingmoai** [microsoft/winget-pkgs#75922]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Like what I commented in https://github.com/microsoft/winget-pkgs/issues/74685#issue-1353227235, both `less.exe` and `lesskey.exe` have to be installed, but it seems like that's not the case for the current package

### Steps to reproduce

1.  `winget install JohnTaylor.less`
2. See only less installed

### Actual behavior

`lesskey.exe` is not installed

### Expected behavior

It should also install `lesskey.exe`

### Environment

```shell
Windows: Windows.Desktop v10.0.22622.586
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2091.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by ItzLevvie** [comment]
This is because the `JohnTaylor.lesskey` package doesn't currently exist in the repository as the pull request which implements this isn't merged; which meant that `PackageDependencies` in the `JohnTaylor.less` had to be commented out from the package since it broke the rebuild publishing pipelines.

Once `JohnTaylor.lesskey` is merged and `PackageDependencies` is uncommented from the package, you will need to enable dependencies inside of the settings.json file.

Here's an example of what it would look like:
```json
{
    "visual": {
        "progressBar": "rainbow"
    },
    "logging": {
        "level": "verbose"
    },
    "source": {
        "autoUpdateIntervalInMinutes": 0
    },
    "network": {
        "downloader": "wininet"
    },
    "experimentalFeatures": {
        "dependencies": true,
        "zipInstall": true
    }
}

```

**Comment by KaranKad** [comment]
PR at https://github.com/microsoft/winget-pkgs/pull/77903 should solve this issue. Once it's merged it will automatically close this issue.
