### ISSUE TITLE
[Package Request]: Add PowerIAST

### ISSUE THREAD

**Issue by alphayama** [microsoft/winget-pkgs#79095]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Alphayama
Publisher Url: https://github.com/alphayama
Package Name: Alphayama.PowerIAST
Description: Easily create diacritic letters to transliterate Sanskrit (and other Indian languages). Based on the PowerAccent project.
Package Version: 1.0
Installer URL: https://github.com/alphayama/PowerIAST/releases/download/1.0/PowerIASTSetup.exe

Current Package Identifier (for new versions): N/A

Note:
Silent installation can be done by running `PowerIASTSetup.exe /S` (case sensitive)

**Comment by infinitepower18** [comment]
You can use [wingetcreate](https://github.com/microsoft/winget-create). Since you are using NSIS, winget will know the silent switch for it. So just install the tool using `winget install wingetcreate` and then run the command `wingetcreate new https://github.com/alphayama/PowerIAST/releases/download/1.0/PowerIASTSetup.exe`.

**Comment by alphayama** [comment]
Thank you for the information
