### ISSUE TITLE
[Package Request]: Rambox

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-pkgs#80626]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Rambox LLC
Publisher Url: https://rambox.app
Package Name: Rambox
Description:  Rambox is a workspace organizer that allows you to unify as many applications as you want, all in one place. It is perfect for those who care about productivity while working with many business and personal apps. 
Package Version: 2.0.6
Installer URL: https://rambox.app/api/download?os=windows

Current Package Identifier (for new versions): 2.0.6

This is different from Rambox.RamboxCE. Community Edition versions were open-source (last one was 0.8). Newer versions are closed-source.

**Comment by mdanish-kh** [comment]
@OfficialEsco - (as you were maintaining this package) Does this require a new PackageIdentifier `Rambox.Rambox` and ARP entries in the manifest (as they don't write to the same registry entry) so that users who have the community edition don't get this version as update? (because the PackageName is same for both community edition and proprietary)

**Comment by vedantmgoyal2009** [comment]
@mdanish-kh can you please add an initial version of `Rambox.Rambox`? I will add all previous versions then.
