### ISSUE TITLE
request for Neofetch

### ISSUE THREAD

**Issue by cake03** [microsoft/winget-pkgs#8571]
Resoiratory: [dylanaraps/neofetch](https://github.com/dylanaraps/neofetch) 
Releases: [dylanaraps/neofetch/Releases](https://github.com/dylanaraps/neofetch/releases)
Liscence: [LICENSE.md](https://github.com/dylanaraps/neofetch/blob/master/LICENSE.md) MIT licence

**Comment by jedieaston** [comment]
Since neofetch ships as a .ps1 file, winget won't be able to install it until we have a way of managing installing from zip files. Once microsoft/winget-cli#140, I (or someone else) will look into getting this added. (I suppose we will need a way of managing loose executables as well, but I presume any solution to the zip file problem has this as an implicit requirement).

**Comment by Trenly** [comment]
@jedieaston - I wasn't able to find the loose executable you mentioned; Can you see if we can support neofetch now that Zips are supported?

**Comment by denelon** [comment]
```
winget search neofetch
Name         Id                  Version Match             Source
-----------------------------------------------------------------
neofetch-win nepnep.neofetch-win 1.2.1   Moniker: neofetch winget
```
