### ISSUE TITLE
Zoom is installed in C:\Windows\System32\config\systemprofile\AppData\Roaming\Zoom

### ISSUE THREAD

**Issue by SamaelAmbrona** [microsoft/winget-pkgs#85999]
### Brief description of your issue

The package Zoom.Zoom is installed in the above mentioned path, which makes it unavailable for the users. It also doesn't create a registry neither is it listed with a Winget list.

### Steps to reproduce

The software, like many other packages, is installed from MDM, using a script that uses Winget.exe install -e --id Zoom.Zoom
As it is installed in this folder, it is not accessible for users, neither appears in the Winget list, in the list of apps installed or in the windows registry.

### Expected behavior

To be installed in some folder accessible for the users

### Actual behavior

It is being installed in the above mentioned folder and cannot be used by users. 
[WinGet-2022-10-20-06-47-40.413.log](https://github.com/microsoft/winget-cli/files/9838410/WinGet-2022-10-20-06-47-40.413.log)

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.2130
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by SamaelAmbrona** [comment]
> @SamaelAmbrona did you try run with:
> 
> `--scope=machine`
> 
> You can read more here: [microsoft/winget-cli#1772](https://github.com/microsoft/winget-cli/issues/1772)
> 
> https://learn.microsoft.com/en-us/windows/package-manager/winget/settings#scope

Hello #fernandog 

No, I haven't tried that. I will thank you very much.

Does it make sense then, to deploy to each computer (User) a JSON file to replace the Winget settings for the one we would prefer? For instance, to always use the Scope machine ...
![image](https://user-images.githubusercontent.com/103502291/197534653-7f0f3567-6f68-41fc-8969-a664f2972766.png)

Best regards

**Comment by DeusMaximus** [comment]
@SamaelAmbrona That's a terrible idea, because now you're relying on the existence of a JSON file which may or may not exist when you go to install an application that requires the --scope=machine parameter to work correctly, and results in a nightmare to troubleshoot for users and technicians alike.

Why can't you just use the --scope parameter with your script? Or change the MDM scope for your Zoom package to run in the user scope? If you're using @Romanitho 's winget-install.ps1 script, you can just do:

`powershell.exe -Executionpolicy Bypass -File winget-install.ps1 -AppIDs "Zoom.Zoom --scope=machine"`

**Comment by SamaelAmbrona** [comment]
@DeusMaximus Thanks for the answer. I can perfectly add the --scope in the script that I am using. I was wondering if the use of a config file (like I read in some posts) would make sense or not, sorry if it is stupid of me to ask.

Best regards
