### ISSUE TITLE
[Package Issue]: Adobe.Acrobat.Reader.64-bit

### ISSUE THREAD

**Issue by SamaelAmbrona** [microsoft/winget-pkgs#86318]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The latest version of Adobe.Acrobat.Reader.64-bit is returning an error ShellExecute installer failed: 150201

### Steps to reproduce

winget install -e --id Adobe.Acrobat.Reader.64-bit --silent --verbose-logs --accept-package-agreements --accept-source-agreements

### Actual behavior

The software is not installing. The installation throws an error 150201

### Expected behavior

Installation should be performed and software available after it

### Environment

```shell
Windows Package Manager v1.3.2691
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.2130
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

### Screenshots and Logs

[WinGet-2022-10-26-16-43-29.559 (Adobe.Acrobat.Reader.64-bit).txt](https://github.com/microsoft/winget-pkgs/files/9870823/WinGet-2022-10-26-16-43-29.559.Adobe.Acrobat.Reader.64-bit.txt)

**Comment by denelon** [comment]
This may help point in the right direction: https://community.adobe.com/t5/acrobat-reader-discussions/installation-error-150201-after-uninstalling-on-windows-10/m-p/12930403

**Comment by SamaelAmbrona** [comment]
Is anybody having a look at this or how does it work?  May I also ask how the updates work? Are they using an update of the app or uninstalling current version and installing the latest one?

**Comment by denelon** [comment]
`winget upgrade <package>` will look to see if a newer version is available in a manifest from one of the configured sources. 

If the package is already installed, and a user runs `winget upgrade <package>` then the installer is simply run again. We have work in progress to avoid this behavior and switch to the upgrade flow. Some packages require special arguments in an upgrade scenario, and some install side-by-side. 

I'm not sure what exception is causing this installer to throw error 150201.

If the manifest specifies "uninstallPrevious" then the existing version is uninstalled first, otherwise the default behavior just passes the arguments in the manifest or the ones provided via "--override" to the installer and executes it.

**Comment by SamaelAmbrona** [comment]
Thank you very much for the explanation. I have tried to find out how it worked but couldn't find any document about it.

> 
> I'm not sure what exception is causing this installer to throw error 150201.
> 
Do you think that you can find / program a solution soon or should I better deploy Acrobat reader on a different way (without Winget)?

**Comment by SamaelAmbrona** [comment]
In case it helps, I have found some workaround for the issue, although I don't know how it can be applied for the Winget package.
https://www.reddit.com/r/SCCM/comments/qqzrcm/adobe_reader_x64_installation_error_exit_code/
https://patchmypc.com/known-issues-and-considerations-when-using-patch-my-pc
![image](https://user-images.githubusercontent.com/103502291/200007920-ff2e9387-c355-4fbb-beaa-34821095ab4e.png)

**Comment by SamaelAmbrona** [comment]
Guys, is there any solution for this? I am still getting the error randomly. Sometimes it works sometimes it doesn't.

**Comment by denelon** [comment]
This is a known issue with the Adobe Acrobat Reader DC installer based on the image above. 

WinGet does support an interactive install with the "--interactive"|"-i" argument.

**Comment by SamaelAmbrona** [comment]
> This is a known issue with the Adobe Acrobat Reader DC installer based on the image above.
> 
> WinGet does support an interactive install with the "--interactive"|"-i" argument.

Does this mean then that there is no solution or what do you mean? 
If the installer is not compatible with Winget, why is it offered in the repository?

**Comment by denelon** [comment]
I was looking at the "workaround" mentioned above. Running `winget install Adobe.Acrobat.Reader.64-bit --interactive` may give more insight into what is failing, or the interactive install may perform more checks/fixes compared to the "--silent" method.

When a manifest is submitted, we perform install verification. If the package installs (and passes our other requirements) then it is accepted. If the package itself has issues with upgrades in certain scenarios, it's likely to be unrelated to WinGet. Unless we can reproduce the situation, there isn't much we can do to see if there is something WinGet might be able to detect or resolve. The same thing would likely happen if you downloaded and ran the installer directly with the same switches. That's what leads me to believe it's an issue with the installer and not WinGet. I could certainly be wrong here which is why I'm looking for a clear way to reproduce the error.

**Comment by totayco** [comment]
Hi Guys,

it seems to be still the issue.

I tried to run this winget command on a newly purchased machine as well as on a new profile and am getting the same results.

any work around on this?


![image](https://user-images.githubusercontent.com/113871465/206954766-40cd52df-96de-4185-b178-01e0e6754819.png)
