### ISSUE TITLE
Firefox Developer Edition get the wrong version and always got upgrade version

### ISSUE THREAD

**Issue by cabins** [microsoft/winget-pkgs#89007]
### Brief description of your issue

![image](https://user-images.githubusercontent.com/2500123/202351142-f889ef70-f20e-4b95-acf4-26b0569fc587.png)

As the picture shows, I installed the latest version of FirefoxDeveoperEdition with `winget install` command, and I still got the upgrade result when I check with `winget upgrade` command.

The installed version winget get is NOT right, `108.0` vs `108.0b2`. 

### Steps to reproduce

- Install firefox developer edition with ` winget install --force Mozilla.Firefox.DeveloperEdition`
- Check upgrade with command `winget upgrade`
- Check whether firefox in the list or not

### Expected behavior

No upgrade prompt with FDE (Firefox Developer Edition)

### Actual behavior

Still prompt to upgrade with FDE

### Environment

```shell
Windows 程序包管理器 v1.3.2691
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.19043.2251
系统体系结构: X64
程序包: Microsoft.DesktopAppInstaller v1.18.2691.0

日志: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
```

**Comment by jedieaston** [comment]
This is because Firefox Developer Edition doesn't put the beta build version into the ARP table, they just write what the eventual stable version number will be. We've been keeping all of the beta builds in this repo separately, so we write the package version as it appears in the file name, <version>b<beta version>.

Two things we could do to fix this:
- Make it so winget can write down the PackageVersion it installed locally, so if it sees that PackageVersion again, it won't try to upgrade to it. (Which doesn't help if apps are uninstalled/upgraded outside of winget, but would reduce the infinite installs to 1).
- Only keep the latest beta build for a particular Firefox release. Probably easiest, even if it makes it so you can't jump to older betas with winget (I doubt many people do that anyway).

**Comment by cabins** [comment]
Aha, now I see. Thank you so much!

**Comment by yugabe** [comment]
I've been having this issue for a while now. I don't think this was resolved when it was closed. Any updates, @jedieaston? Thanks.

**Comment by Terafugia** [comment]
Issue still occurs for me. Search results only found this one - since been closed by the OP - Yet with no resolution.
