### ISSUE TITLE
Range GET requests are not supported by the copy source

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-pkgs#91]
It looks like we have a problem with Range GET requests. #85

**Comment by sundhaug92** [comment]
Looks like an undocumented requirement. I get why it's there but I think it should be removed

**Comment by stedaniels** [comment]
The winget cli supports range requests.
A manifest that specifies a Url that references a web server that doesn't support range requests/streams will correctly fail-over to download, as per https://github.com/microsoft/winget-cli/blame/cc7904cd23bf1cdb1178a9dd8e634edf82d51e68/src/AppInstallerCLICore/Workflows/InstallFlow.cpp#L124.

The [validation-pipeline.yaml](https://github.com/microsoft/winget-pkgs/blob/master/DevOpsPipelineDefinitions/validation-pipeline.yaml) is the pipeline that appears to be broken, as far as I can tell it's the '[Installers Scan](https://github.com/microsoft/winget-pkgs/blob/master/DevOpsPipelineDefinitions/validation-pipeline.yaml#L98)' task.  I'm not really familiar with Azure pipelines but it appears to be calling executables/functions that haven't been open sourced.  Otherwise I would have attempted to find and fix the problem and sent a PR.

An example of a manifest that passes local validation but fails the pipelines is HeidiSQL.

`PS C:\devel\winget\winget-pkgs> winget install -m manifests\AnsgarBecker\HeidiSQL\11.0.0.5919.yaml
Found HeidiSQL [AnsgarBecker.HeidiSQL]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.heidisql.com/installers/HeidiSQL_11.0.0.5919_Setup.exe
  ██████████████████████████████  22.1 MB / 22.1 MB
Successfully verified installer hash
Installing ...
Successfully installed!`

This can be found failing here: https://github.com/microsoft/winget-pkgs/pull/1914

The output from the 'Installers Scan' is here: https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=90013&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d&l=41


I don't want to minimise the issue, obviously range requests have been around for quite a while, but we can't expect everyone to renovate their server infrastructure.  The winget cli supports failing over, so drop these failures down to warnings and move on?

**Comment by floh96** [comment]
@denelon Is the milestone for this issue correct please prioritise since a lot of packages can't be added to winget because of this issue.

**Comment by denelon** [comment]
@floh96 We've been independently working milestones between the client and the services behind this repository. The fix for this was just pushed into production. We're going to re-run and validate all of the PRs to see how many of them will complete now before closing this issue.

**Comment by floh96** [comment]
> @floh96 We've been independently working milestones between the client and the services behind this repository. The fix for this was just pushed into production. We're going to re-run and validate all of the PRs to see how many of them will complete now before closing this issue.
Heidi SQL #950 just passed validation. Thanks for fixing this.

**Comment by denelon** [comment]
It looks like all of the issues with "Range Get requests" are passing now.  I'm going to go ahead and close this issue. Feel free to open it back up if anything else fails due to this reason.
