### ISSUE TITLE
[Package Issue]: OpenRCT2.OpenRCT2 wrong version advertisement leads to update loop

### ISSUE THREAD

**Issue by markusdd** [microsoft/winget-pkgs#94743]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

update loop caused by wrong version (0.4.3 is advertised here, but in reality 0.4.3 is followed by a hash and branch name)

### Steps to reproduce

install OpenRCT2, then run an update via winget

### Actual behavior

update is offered again and again

### Expected behavior

update happens and is not offered again

### Environment

```shell
> winget --info
Windows-Paket-Manager v1.4.10173
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22621.1105
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.19.10173.0
```

### Screenshots and Logs

Here is the relted ticket at OpenRCT2, which rightfully redirected here:
https://github.com/OpenRCT2/OpenRCT2/issues/19072

**Comment by denelon** [comment]
What does the output from `winget list` show for the installed version and the available version?

**Comment by mdanish-kh** [comment]
```pwsh
~ winget list openrct2
Name                         Id                Version             Available Source
-----------------------------------------------------------------------------------
OpenRCT2 0.4.3master-285e0fc OpenRCT2.OpenRCT2 0.4.3master-285e0fc 0.4.3     winget
```
DisplayVersion is different from marketing version. I noticed something while going through the older manifests here [manifests/o/OpenRCT2](https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenRCT2/OpenRCT2). Some releases use the same DisplayVersion as Marketing versions while others use `MarketingVersion<branch_name><commit_hash>` as DisplayVersion. This behavior can be fixed by either changing the PackageVersion of the recent release to `0.4.3master-285e0fc` or use AppsAndFeaturesEntries.

I'm more tempted towards the latter to have all versions use the Marketing version but that would also require going through the previous releases and adding AppsAndFeaturesEntries to every manifest to avoid an upgrade loop again 😅 I'll open PRs to fix this behavior

**Comment by markusdd** [comment]
exactlym thanks for providing this here.

This discrepancy needs to be fixed, otherwise winget cannot be used for OpenRCT2.

**Comment by denelon** [comment]
@mdanish-kh,

You're getting really good at this! I think we need to look at adding some logic around packages with manifests in this inconsistent state.

**Comment by mdanish-kh** [comment]
@markusdd Can you please check the output of `winget list openrct2`? It should be matching this now:

```pwsh
~ winget list openrct2
Name                         Id                Version Source
--------------------------------------------------------------
OpenRCT2 0.4.3master-285e0fc OpenRCT2.OpenRCT2 0.4.3   winget
```

**Comment by markusdd** [comment]
Yup, I confirm:

```
winget list openrct2
Name                         ID                Version Quelle
--------------------------------------------------------------
OpenRCT2 0.4.3master-285e0fc OpenRCT2.OpenRCT2 0.4.3   winget
```

**Comment by mdanish-kh** [comment]
Close with reason: Resolved in above linked PRs;
