### ISSUE TITLE
How to move from existing singleton to multi-file manifests?

### ISSUE THREAD

**Issue by dpprdan** [microsoft/winget-pkgs#9476]
# Description 

Some existing manifests (e.g. for [pgAdmin](https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/PostgreSQL)) are duplicated for different installers (x86 and x64 in this case). How should we proceed with these moving forward?

1. Should the existing manifests be consolidated into multi-file manifests in the pgAdmin directory? Or leave them as-is? (To further complicate things there aren't manifests for both installers for all recent pgAdmin versions).
2. Where should manifests for future versions live, i.e. where would I create the manifests for pgAdmin v5.1? I assume they should preferably be multi-file manifests?

3. Only partly related: What's the general policy for new versions? Is it okay to update existing manifests to the new versions (essentially erasing the manifests for the previous version - this [has happened for pgAdmin](https://github.com/microsoft/winget-pkgs/pull/8081/files)) or should a new manifest be created always (always assuming that the previous version is still available at the source).

**Comment by denelon** [comment]
@dpprdan I've been looking at Visual Studio Code as another example.

I think we want a single (multi-file) manifest for packages like this. It may mean we need to create a new package for the program with the multiple installers. We're still working on [User vs. System](https://github.com/microsoft/winget-cli/issues/149), but the Architecture is auto-selected by the client to be the most optimal one for the machine.

For pgAdmin I would suggest creating the multi-file manifest in the /p/PostgreSQL/pgAdmin path to add support for both installers since that package name doesn't have the x86 architecture specified.

For a given version, I would delete the singleton manifest and add the multi-file manifest.

**Comment by denelon** [comment]
For new versions of packages, I'd create a new manifest (assuming the URL is unique to a specific version). If the URL for the installer is the same for multiple versions, I'd delete the old manifest.

**Comment by dpprdan** [comment]
Thanks for changing all the manifests to multi-file, @OfficialEsco! 🚀 

Tagging the PRs for deleting the existing x64 manifests for completeness: #9536, #9537, #9538, #9539, #9540.

> It may mean we need to create a new package for the program with the multiple installers.

Sorry, I don't follow, @denelon. Could you elaborate, please?

Re "What's the general policy for new versions?" I assume it's "create a new manifest" (as long as the previous version is still available at the source). Maybe this could be documented somewhere (if it isn't already and I missed it)?

**Comment by denelon** [comment]
@dpprdan it looks like @OfficialEsco did what I had suggested.

The multi-file manifest supports multiple installers, locales, architectures, and a few other additional enhancements. Our intent is to support a single logical package across those dimensions. Rather than needing a set of "packages", we're working towards a model where there is a single package. That will allow users to have preferences for which installer is used by default, and still enable command-line switches to specify explicit choices.

I've been playing whack-a-mole with documentation regarding manifest creation. I'm hoping to find those last few pesky references so I can work on clear guidance. I'm going to add the Issue-Docs label to this Issue to remind myself about this particular area.

**Comment by denelon** [comment]
I believe the best scenario related to package versions is to retain manifests for every valid version that may still be installed. When a new version is released, a new manifest should be created.

The two primary exceptions are when there is only a vanity URL for distribution and when a package author/publisher wishes an older version to be removed.

**Comment by jedieaston** [comment]
I've been writing a [PowerShell module ](https://github.com/jedieaston/WinGetHelpers) for automating activities in the repository, and I wrote a function (Convert-WinGetSingletonToMultifile) that does this, if anyone wants a quick way to get a manifest capable of having multiple architectures. 

There's certain corner cases that I'm still working around, but maybe it helps. I've been using it coupled with Update-WinGetManifest to add architectures to some different packages, and so far it's gone well.

**Comment by OfficialEsco** [comment]
Can this be closed as we're way past this stage? 🤔

**Comment by denelon** [comment]
Yeah, this was mostly for documentation. We will have more documentation as we get closer to the 1.1 schema, but I'll go ahead and close this one.
