### ISSUE TITLE
Fabric bot Automerge does not respect minMinutesOpen

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#96182]
According to the event timeline, #96035 was open for only 4 minutes and 65 seconds. This conflicts with the rule which indicates a PR be open for a minumum of 5 minutes before automatically merging.

https://github.com/microsoft/winget-pkgs/blob/d0ade226a314aa87e46ad23588175aead1e1c403/.github/fabricbot.json#L796-L809

* Ref https://api.github.com/repos/microsoft/winget-pkgs/issues/96035
* Ref https://api.github.com/repos/microsoft/winget-pkgs/issues/96035/timeline

* Related to https://github.com/microsoft/winget-pkgs/issues/95543

**Comment by denelon** [comment]
Related to:
* https://github.com/microsoft/winget-pkgs/issues/95543

This is more likely a GitHub thing, but maybe fabric bot could do something here.

**Comment by astatide** [comment]
This is unfortunately and definitely a GitHub thing : ( I'm still trying to find who to contact about making changes to the automerge permissions on GH but in between out of offices, etc, it's a little hard to track down!

I was hoping to come in and have a little more insight as to whether we can work around it in FabricBot or just make more granular controls at the automerge level (which is my hope), but I'm not likely to have an update until next week at the earliest when people are no longer out of office.  There will be options _regardless_ but I'm a little afraid of suggesting them as a wide scale solution due to the traffic they might create.

I'll continue brainstorming options on our end and pursuing leads with GH itself, as I think native solutions integrated into the core would be much more appropriate for this, personally (speaking as a developer, not as a person making product promises!).

**Comment by Trenly** [comment]
Closing this issue as it is not planned for GitOps implementation
