### ISSUE TITLE
Users can cancel auto-merge on their own PR's

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#96181]
The previous behavior was that auto-merge could not be canceled by a user to prevent PR's from piling up. 
With the new behavior, users can cancel Auto-Merge on their own PR's with no way to re-enable it.

* Ref https://github.com/microsoft/winget-pkgs/pull/96100

* Related to https://github.com/microsoft/winget-pkgs/issues/95543

**Comment by denelon** [comment]
Related to:
* https://github.com/microsoft/winget-pkgs/issues/95543

This is more likely a GitHub thing, but maybe fabric bot could do something here.

**Comment by astatide** [comment]
Looking into this more... this is definitely a change due to the fact that we've basically gone from running our own infrastructure and auto merge functionality to 'simply enabling' the native automerge under certain conditions.

I'm willing to bet we could fix it with a new repo-defined task if it's not considered desirable behavior; basically, capture the event in which a user cancels the PR and then simply re-enable it, although that might lead to excess activity.  Still, I think that _should_ be something that's more or less doable now.  I'll have to check the new code base we're running on to see if we have a "cancelled automerge" event / how it comes in (nothing obvious springs to mind).

Other than writing up the template for how to do this in the new YML format when we get it out there, I'm not sure there's anything we can do code wise on our end.  I'll reference this in our backlog as a potential documentation / investigation to see how we can reach feature parity, so to speak.

**Comment by astatide** [comment]
Out of curiousity, how important is this feature for your workflow?

**Comment by Trenly** [comment]
> Out of curiousity, how important is this feature for your workflow?

I think it would be rare for users to cancel their own auto-merge, so this is probably an edge case; However, it is important that when a PR meets all the criteria, it gets merged. I think there may be workarounds with the new format such as having a "merge" action instead of using automerge, but if PR's aren't merged, updates to packages won't be available to end users.

**Comment by astatide** [comment]
https://github.com/microsoft/winget-pkgs/issues/96183

These two have the same root cause (how GH handles automerge).  It's technically a bug that we don't have the full support for automerge handled (I have some PRs out to 'fix' said bug by adding in what we need) but I still would like to see if there's a policy option that could be used, as fighting against GH with FabricBot actions is... not ideal in terms of traffic and etc.   So in terms of re-enabling automerge there might be a better solution.

Having said dealing with automerge related events are a thing that we receive in the app, so at the very least they can be utilized in the workflow graph.

**Comment by astatide** [comment]
I've started trying to reach out to the team at GH responsible for automerge just to get the ball rolling; in the meantime I've made some very tiny changes to the gitops base to make sure these events are forwarded on to FabricBot so that users can apply workarounds (as well as reacting to automerge events in other situations too!).

Let's keep in contact here re: how the automerge change in general is disrupting your workflow, as that might influence our backlog and how we prioritize pushing features out if things aren't able to worked with as is.!

**Comment by denelon** [comment]
OK, maybe it could be another rule to add a label for our team to know which ones we need to manually merge, and some message to the author regarding the disable automerge coming from GitHub.

**Comment by Trenly** [comment]
I'm going to close this as with the new GitOps framework we can check to re-enable automerge on any Pull_Request event, which should trigger the rule even when a user tries to cancel the automerge on their own PR
